### ISSUE TITLE
Failing to compile NGINX with PQ openssl fork

### ISSUE THREAD

**Issue by RicardoGaGu** [open-quantum-safe/openssl#103]
HI! I'm trying to compile the PQ OpenSSL fork into NGINX, I've run into some problems when building nginx wirth openssl underneath. I'll show my Dockerfile to clarify my procedure for installing Nginx. I have tested the TLS demo and works fine, but when configuring Nginx on Ubuntu 18.04 it fails. I kindly ask if anyone know how to solve this problem.

```
FROM ubuntu:18.04

### Building NGINX from source with post quantum openssl for TLS connections
RUN apt update && apt upgrade -y
RUN apt install wget autoconf automake libtool libssl-dev make unzip xsltproc git -y
RUN apt install build-essential -y

### Step 1: Build required libraries: pcre, zlib and quantum safe openssl

### PCRE
RUN wget ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.42.tar.gz && \
 tar -zxf pcre-8.42.tar.gz && \
 cd pcre-8.42 && \
 ./configure && \
 make && \
 make install
### ZLIB
RUN wget http://zlib.net/zlib-1.2.11.tar.gz && \
 tar -zxf zlib-1.2.11.tar.gz && \
 cd zlib-1.2.11 && \
 ./configure && \
 make && \
 make install


### Install liboqs
WORKDIR /usr/local/

RUN git clone --branch OQS-OpenSSL_1_1_1-stable https://github.com/open-quantum-safe/openssl.git

RUN git clone --branch master https://github.com/open-quantum-safe/liboqs.git

WORKDIR /usr/local/liboqs
RUN autoreconf -i
RUN ./configure --prefix=/usr/local/openssl/oqs --enable-shared=no
RUN make -j
RUN make install

### Install openssl
WORKDIR /usr/local/openssl
RUN ./config --prefix=/usr/local/openssl -Wl,-rpath -Wl,/usr/local/openssl/oqs/lib
RUN make -j

RUN cp libcrypto.so.1.1 ./oqs/lib
RUN cp libssl.so.1.1 ./oqs/lib

WORKDIR /

### Step 2: Download NGINX and RTMP module
RUN wget https://nginx.org/download/nginx-1.15.11.tar.gz && \
 tar zxf nginx-1.15.11.tar.gz

RUN wget https://github.com/arut/nginx-rtmp-module/archive/master.zip && \
 unzip master.zip

RUN rm -rf *.tar.gz

### Step 3: Build and install NGINX
RUN wget https://nginx.org/download/nginx-1.15.11.tar.gz && \
 tar zxf nginx-1.15.11.tar.gz

RUN   cd nginx-1.15.11 && ./configure \
--with-cc-opt="-I /usr/local/openssl/oqs/include/" \
--with-ld-opt="-L /usr/local/openssl/oqs/lib/"\
--sbin-path=/usr/local/nginx/nginx \
--conf-path=/usr/local/nginx/nginx.conf \
--pid-path=/usr/local/nginx/nginx.pid \
--with-pcre=../pcre-8.42 \
--with-zlib=../zlib-1.2.11 \
--with-openssl=/usr/local/openssl \
--with-http_ssl_module \
--with-stream \
--with-mail=dynamic \
--add-module=/nginx-rtmp-module-master && \
make && \
make install
```

The error is the following:

/usr/local/openssl/.openssl/lib/libssl.a(s3_lib.o): In function `ssl3_clear':
s3_lib.c:(.text+0x51b): undefined reference to `OQS_KEM_free'
/usr/local/openssl/.openssl/lib/libssl.a(extensions_clnt.o): In function `tls_construct_ctos_key_share':
extensions_clnt.c:(.text+0x18af): undefined reference to `OQS_KEM_new'
extensions_clnt.c:(.text+0x1952): undefined reference to `OQS_KEM_keypair'
extensions_clnt.c:(.text+0x199c): undefined reference to `OQS_MEM_secure_free'
extensions_clnt.c:(.text+0x19a4): undefined reference to `OQS_MEM_insecure_free'
extensions_clnt.c:(.text+0x19c2): undefined reference to `OQS_KEM_free'
/usr/local/openssl/.openssl/lib/libssl.a(extensions_clnt.o): In function `tls_parse_stoc_key_share':
extensions_clnt.c:(.text+0x3c96): undefined reference to `OQS_MEM_secure_free'
extensions_clnt.c:(.text+0x3cb4): undefined reference to `OQS_MEM_secure_free'
extensions_clnt.c:(.text+0x3cd2): undefined reference to `OQS_KEM_free'
extensions_clnt.c:(.text+0x3d77): undefined reference to `OQS_KEM_decaps'
/usr/local/openssl/.openssl/lib/libssl.a(extensions_srvr.o): In function `tls_construct_stoc_key_share':
extensions_srvr.c:(.text+0x3769): undefined reference to `OQS_KEM_new'
extensions_srvr.c:(.text+0x37be): undefined reference to `OQS_KEM_encaps'
extensions_srvr.c:(.text+0x3906): undefined reference to `OQS_MEM_secure_free'
extensions_srvr.c:(.text+0x390e): undefined reference to `OQS_KEM_free'
extensions_srvr.c:(.text+0x3aeb): undefined reference to `OQS_MEM_secure_free'
extensions_srvr.c:(.text+0x3af3): undefined reference to `OQS_KEM_free'
/usr/local/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): In function `pkey_oqs_digestverify':
oqs_meth.c:(.text+0x101): undefined reference to `OQS_SIG_verify'
/usr/local/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): In function `pkey_oqs_digestsign':
oqs_meth.c:(.text+0x62f): undefined reference to `OQS_SIG_sign'
/usr/local/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): In function `oqs_free':
oqs_meth.c:(.text+0x1d0e): undefined reference to `OQS_SIG_free'
/usr/local/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): In function `oqs_key_init':
oqs_meth.c:(.text+0x1df9): undefined reference to `OQS_SIG_new'
oqs_meth.c:(.text+0x1f30): undefined reference to `OQS_SIG_free'
/usr/local/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): In function `oqs_priv_decode':
oqs_meth.c:(.text+0x22f6): undefined reference to `OQS_SIG_free'
/usr/local/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): In function `pkey_oqs_keygen':
oqs_meth.c:(.text+0x2528): undefined reference to `OQS_SIG_new'
oqs_meth.c:(.text+0x273c): undefined reference to `OQS_SIG_keypair'
oqs_meth.c:(.text+0x2778): undefined reference to `OQS_SIG_free'
oqs_meth.c:(.text+0x2810): undefined reference to `OQS_SIG_free'
/usr/local/openssl/.openssl/lib/libcrypto.a(oqs_meth.o): In function `oqs_pub_decode':
oqs_meth.c:(.text+0x2b6a): undefined reference to `OQS_SIG_free'
collect2: error: ld returned 1 exit status
objs/Makefile:323: recipe for target 'objs/nginx' failed
make[1]: Leaving directory '/nginx-1.15.11'
make[1]: *** [objs/nginx] Error 1
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

Thanks!

**Comment by dstebila** [comment]
Hi @RicardoGaGu, we haven't got build instructions for nginx (but probably should).  It looks to me like the nginx build system isn't being directed to link against liboqs.  Can you try adding `-loqs` somewhere, for example added on to the `--with-ld-opt` argument?

**Comment by RicardoGaGu** [comment]
Hi @dstebila, thanks for the quick reply, adding -loqs on the --with-ld-opt argument does not seem to be a valid option:

Error:

---> Running in 91952e53ed0a
checking for OS
 + Linux 4.18.0-15-generic x86_64
checking for C compiler ... found
 + using GNU C compiler
 + gcc version: 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1) 
checking for gcc -pipe switch ... found
checking for --with-ld-opt="-loqs" ... not found
./configure: error: the invalid value in --with-ld-opt="-loqs"

The command '/bin/sh -c cd nginx-1.15.11 && ./configure --with-cc-opt="-I /usr/local/openssl/oqs/include/" --with-ld-opt="-loqs" --sbin-path=/usr/local/nginx/nginx --conf-path=/usr/local/nginx/nginx.conf --pid-path=/usr/local/nginx/nginx.pid --with-pcre=../pcre-8.42 --with-zlib=../zlib-1.2.11 --with-openssl=/usr/local/openssl --with-http_ssl_module --with-stream --with-mail=dynamic --add-module=/nginx-rtmp-module-master && make && make install' returned a non-zero code: 1

**Comment by dstebila** [comment]
I think you'd have to *add* `-loqs` to the existing argument, so it becomes:
```
--with-ld-opt="-L /usr/local/openssl/oqs/lib/ -loqs"
```

**Comment by RicardoGaGu** [comment]
Ok, I just tried it with no success, the same error keeps appearing.

collect2: error: ld returned 1 exit status
objs/Makefile:323: recipe for target 'objs/nginx' failed
make[1]: Leaving directory '/nginx-1.15.11'
make[1]: *** [objs/nginx] Error 1
make: *** [build] Error 2
Makefile:8: recipe for target 'build' failed

**Comment by RicardoGaGu** [comment]
This the command with I think ld parameters that appear in my nginx compile logs:

-L /usr/local/openssl/oqs/lib/ -loqs -ldl -lpthread -lcrypt ../pcre-8.42/.libs/libpcre.a /usr/local/openssl/.openssl/lib/libssl.a /usr/local/openssl/.openssl/lib/libcrypto.a -ldl -lpthread ../zlib-1.2.11/libz.a \
-Wl,-E

**Comment by dstebila** [comment]
Okay, I'd hoped the fix was simple but apparently not.  I'll have to sit down with the build process and try to reproduce/debug, might take a few days to get back to you on this.

**Comment by RicardoGaGu** [comment]
Okay, many thanks, any kind of feedback is appreciated. I'd be around and I will also get back to you if I find a solution to this.

**Comment by dstebila** [comment]
Sometimes order matters.  Can you try to see if there's any way to get the `-loqs` argument to appear after the libcrypto.a?

**Comment by christianpaquin** [comment]
I've successfully built nginx using the OpenSSL OQS fork; my process is [documented on our wiki](https://github.com/open-quantum-safe/openssl/wiki/Running-TLS-1.3-in-nginx). I've faced a few quirks as well; as documented on the page, I had to modify the obj/Makefile to remove invalid path to openssl, I've commented out the recompilation of openssl, and I added a liboqs.a directly. Let me know if that helps.

**Comment by RicardoGaGu** [comment]
Sorry for the lateness, but I've finally been able to compile your OpenSSL fork into Nginx. I've followed Christian's suggestions and I think the issue is best solved by manually editing Nginx makefile and incorporating the liboqs.a at the end of the linker options. Order does matter indeed!

**Comment by RicardoGaGu** [comment]
Hi, I feel obligated to comment here again. I did succeed to compile the pqc enabled openssl fork on a nginx web server and did some succesful tests with another pqc openssl client container, but I've built the docker image without cache settings (I follow all the steps of wiki documentation in the dockerfile instructions) and it seems that some modifications on the stable branch of this openssl fork have introduced some new errors during the building of the nginx. They seem to be openssl related and that's why I suspect some changes have been going on. Nonetheless, I post here the error to see if anyone can make sense out of it:

> src/event/ngx_event_openssl.c: In function 'ngx_ssl_session_id_context':
src/event/ngx_event_openssl.c:3123:10: error: implicit declaration of function 'EVP_MD_CTX_create'; did you mean 'EVP_MD_CTX_free'? [-Werror=implicit-function-declaration]
     md = EVP_MD_CTX_create();
          ^~~~~~~~~~~~~~~~~
          EVP_MD_CTX_free
src/event/ngx_event_openssl.c:3123:8: error: assignment makes pointer from integer without a cast [-Werror=int-conversion]
     md = EVP_MD_CTX_create();
        ^
src/event/ngx_event_openssl.c:3203:5: error: implicit declaration of function 'EVP_MD_CTX_destroy'; did you mean 'EVP_MD_CTX_reset'? [-Werror=implicit-function-declaration]
     EVP_MD_CTX_destroy(md);
     ^~~~~~~~~~~~~~~~~~
     EVP_MD_CTX_reset
cc1: all warnings being treated as errors
objs/Makefile:848: recipe for target 'objs/src/event/ngx_event_openssl.o' failed
make[1]: Leaving directory '/nginx-1.17.0'
make[1]: *** [objs/src/event/ngx_event_openssl.o] Error 1
make: *** [build] Error 2
Makefile:8: recipe for target 'build' failed
The command '/bin/sh -c make' returned a non-zero code: 2



Also, these are warnings , but the compilation of Nginx goes with the -Werror flags that automatically converts them into errors during building. I tried avoiding this flag but the built nginx service start results on a segmentation fault (core dump).

Thank you.

**Comment by dstebila** [comment]
Are you using our OpenSSL 1.0.2 branch or our OpenSSL 1.1.1 branch?  OpenSSL changed names of some EVP\_MD\_CTX function names from 1.0.2 to 1.1.1, so that may be related to the error you are experiencing.

**Comment by RicardoGaGu** [comment]
I'm using the OQS-OpenSSL_1_1_1-stable branch. Could it be that another configured openssl library is on my docker image? All the path point to the pqc enabled openssl fork though.

**Comment by csosto-pk** [comment]
> I'm using the OQS-OpenSSL_1_1_1-stable branch. Could it be that another configured openssl library is on my docker image? All the path point to the pqc enabled openssl fork though.

@RicardoGaGu  , we dealt with this issue when building the latest nginx with OQS-OpenSSL_1_1_1-stable as well. The reason is the one @dstebila mentions. OpenSSL 1.1.1 changed the EVP_MD_CTX calls and nginx uses the ones from OpenSSL 1.0.2. 

To fix it  we had to go in src/event/ngx_event_openssl.c in the nginx source directory and rename the ```EVP_MD_CTX_create()``` and ```EVP_MD_CTX_destroy()``` calls to ```EVP_MD_CTX_new()``` and ```EVP_MD_CTX_free()```. respectively. And then build nginx again of course.

**Comment by RicardoGaGu** [comment]
> > I'm using the OQS-OpenSSL_1_1_1-stable branch. Could it be that another configured openssl library is on my docker image? All the path point to the pqc enabled openssl fork though.
> 
> @RicardoGaGu , we dealt with this issue when building the latest nginx with OQS-OpenSSL_1_1_1-stable as well. The reason is the one @dstebila mentions. OpenSSL 1.1.1 changed the EVP_MD_CTX calls and nginx uses the ones from OpenSSL 1.0.2.
> 
> To fix it we had to go in src/event/ngx_event_openssl.c in the nginx source directory and rename the `EVP_MD_CTX_create()` and `EVP_MD_CTX_destroy()` calls to `EVP_MD_CTX_new()` and `EVP_MD_CTX_free()`. respectively. And then build nginx again of course.

Your commentary helped me a lot. I was able to succesfully build nginx with the OQS-OpenSSL_1_1_1-stable branch.

**Comment by xvzcf** [comment]
For posterity, the instructions to build nginx are no longer on the wiki page and have been moved [here](https://github.com/open-quantum-safe/oqs-software).
