### ISSUE TITLE
Building as shared library fails

### ISSUE THREAD

**Issue by panburana** [open-quantum-safe/openssl#111]
When attempt to build the OQS-OpenSSL_1_1_1-stable branch as a shared library with the following configure statement:
```sh
./Configure shared linux-x86_64 -lm
```
make fails with the following error:
``` sh
ranlib libssl.a || echo Never mind.
Error: EVP_MD_CTX_create does not have a number assigned
Makefile:762: recipe for target 'libcrypto.map' failed
make[1]: *** [libcrypto.map] Error 25
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/home/peter/Documents/openssl'
Makefile:172: recipe for target 'all' failed
make: *** [all] Error 2
```

Is there something special that needs to be done in order to build the fork as a shared library?

*edit* specify branch

**Comment by xvzcf** [comment]
Hi, could you checkout [this PR](https://github.com/open-quantum-safe/openssl/pull/117) and see if it solves the issue?

**Comment by panburana** [comment]
Yep, I'm able to build as a shared library now. Thank you again for resolving that!
