### ISSUE TITLE
Code point interoperability

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssl#116]
The current 1.1.1 branch breaks interoperability with the previous tagged release due to different assignment of the code points for the PQ KEM algs. Up to the integration of templating code, the code points (used in TLS to specify the selected "curve") were assigned manually and care was taken to keep previously defined values the same, to ensure that client/server remained interoperable between versions or implementations (e.g., openssl and boringssl). Templating simplifies the integration of new algs, but overwrites previous code point values. This means that, in the future, any changes of the OQS supported list of algs will result in different code point values.

We should design a mechanism to assign specific code points to an algorithm, both if this is specified in a standard, or to preserve interop between releases. We support this already for signature OIDs.

If we break compatibility in this release, we should document that and bump the release version number accordingly.

**Comment by dstebila** [comment]
@xvzcf with the templating approach, is it possible to specify the code points in the configuration file so that they can be kept consistent?

**Comment by xvzcf** [comment]
Not at the moment, but the modifications to do so should be easy enough.

**Comment by dstebila** [comment]
@xvzcf It seems like something we should do -- code point compatibility for, at least, KAT compatible algorithms.  

@christianpaquin We haven't formally been numbering our OpenSSL releases, just calling them "OQS-OpenSSL 1.1.1 YYYY-MM snapshot release", so we don't have a semantic numbering system implying compatibility.  Should we?

**Comment by christianpaquin** [comment]
I guess it would be confusing to add a second layer of versioning on top of OpenSSL's. The snapshot release id is ok if we keep compatibility intact.

**Comment by christianpaquin** [comment]
The ability to specify code points in config will become increasingly valuable as these algorithms start appearing in standards.

**Comment by xvzcf** [comment]
My earlier comment was inaccurate: The KEM NID's already have to be manually specified in the `generate.yml` file, and so no additional work is needed there. It is the signature scheme bitmasks in `ssl/ssl_locl.h` that are assigned in an automatic fashion, which might cause inter-operability problems.

**Comment by xvzcf** [comment]
The signature NIDs are assigned automatically in that the order in which the signature algorithms are specified in `crypto/objects/objects.txt` determines the NID assigned in `include/openssl/obj_mac.h`. 

This means interoperability is preserved if entries are only appended to the file. Right now, the templating code adds an algorithm, then all it's hybrid variants before moving on to the next one. So, if an algorithm gets a new hybrid variant, that would affect NID assignment.

**Comment by xvzcf** [comment]
In short:

1) KEM NID's (and therefore CurveID's) already have to be manually specified in the `generate.yml` file, so no additional work is needed there.

2) The templating code assigns signature OIDs as described [here](https://github.com/open-quantum-safe/openssl/wiki/Contributing-Guide) under the "Adding an authentication algorithm" section. Adding (or re-ordering) hybrid variants will affect inter-operability, and so additional work is needed here.

**Comment by dstebila** [comment]
Can you check which curve IDs are different between the current version and previous releases of OQS-OpenSSL-1.1.1?  If there are differences we should decide whether to make them align, or whether to acknowledge that in the release notes, but plan to keep alignment going forward.

**Comment by xvzcf** [comment]
From examining `ssl_locl.h` at the [1.1.1c tag](https://github.com/open-quantum-safe/openssl/blob/8c4e1a72c2e892d6d4b9903769ad1f29f95a1dae/ssl/ssl_locl.h#L559) (before templating was added) and at the [1.1.1d tag](https://github.com/open-quantum-safe/openssl/blob/5ca5e645180c93fa4a1c39efa6a96f1ef2f2bab6/ssl/ssl_locl.h#L600) (after templating was added), at the very least, all the post-quantum only schemes and variants except for `KEM_DEFAULT` have differing curve IDs.

**Comment by dstebila** [comment]
> From examining `ssl_locl.h` at the [1.1.1c tag](https://github.com/open-quantum-safe/openssl/blob/8c4e1a72c2e892d6d4b9903769ad1f29f95a1dae/ssl/ssl_locl.h#L559) (before templating was added) and at the [1.1.1d tag](https://github.com/open-quantum-safe/openssl/blob/5ca5e645180c93fa4a1c39efa6a96f1ef2f2bab6/ssl/ssl_locl.h#L600) (after templating was added), at the very least, all the post-quantum only schemes and variants except for `KEM_DEFAULT` have differing curve IDs.

Thanks. It doesn't seem like it would be difficult for us to keep the curve IDs consistent, the only annoyance I can think of is that we might have some gaps since we've dropped some algorithms.

**Comment by xvzcf** [comment]
It shouldn't be difficult at all since we do specify every single curve ID in the `generate.yml` file.

**Comment by xvzcf** [comment]
[This PR](https://github.com/open-quantum-safe/openssl/pull/120) addresses signature OID consistency.

**Comment by dstebila** [comment]
Fixed by #120.
