### ISSUE TITLE
New OQS breaks the build

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssl#12]
Latest OQS update breaks the OpenSSL build. "./config" results in the following error:

cd vendor/liboqs && make links
make[1]: Entering directory '/mnt/c/temp/openssl/vendor/liboqs'
make[1]: *** No rule to make target 'links'.  Stop.
make[1]: Leaving directory '/mnt/c/temp/openssl/vendor/liboqs'
Makefile:451: recipe for target 'links' failed
make: *** [links] Error 2

The config script shouldn't be "making" vendor/liboqs. This is currently done in "make".

**Comment by smashra** [comment]
As far as I can see this problem exists in the main (OpenSSL_1_0_2-stable)
branch too.

It's happening because Makeifle doesn't exist under vendor/liboqs because
autoreconf is  not called.
It gets called when make is called.

**Comment by christianpaquin** [comment]
I noticed. Do you see an easy fix? Put a dummy makefile in OQS or modify openssl's config script?

On Oct 5, 2017, at 9:09 AM, smashra <notifications@github.com<mailto:notifications@github.com>> wrote:

As far as I can see this problem exists in the main (OpenSSL_1_0_2-stable)
branch too.

It's happening because Makeifle doesn't exist under vendor/liboqs because
autoreconf is not called.
It gets called when make is called.

**Comment by smashra** [comment]
Looking into it.

**Comment by s24mishra** [comment]
Fix is available under liboqs_update branch.

**Comment by smashra** [comment]
make depend ;make test now work fine.
make test is not causing the liboqs to rebuild it's only calling autoreconf -i;./configure;make but actually not building because it figures the build has already happened, if not, then only it actually builds.

**Comment by kevinmkane** [comment]
I'm seeing this issue on the current HEAD of OpenSSL_1_0_2-stable and liboqs_update, which is commit 608bc3a8 and a fix for this issue. 

I'm seeing this output from a './config shared && make' on an Ubuntu 16.04 machine:

make[1]: Entering directory '/home/kkane/src/walrus/walrus/openvpn/build/repos/openssl-oqs/vendor/liboqs'
/bin/mkdir -p include/oqs
cp -f src/common/common.h include/oqs
cp: 'src/common/common.h' and 'include/oqs/common.h' are the same file
Makefile:1330: recipe for target 'links' failed
make[1]: *** [links] Error 1
make[1]: Leaving directory '/home/kkane/src/walrus/walrus/openvpn/build/repos/openssl-oqs/vendor/liboqs'
Makefile:284: recipe for target 'build_liboqs' failed
make: *** [build_liboqs] Error 2

Is this still an artifact of this open issue, do you think, or might something else be going on?

**Comment by dstebila** [comment]
Hi Kevin, we just tried rebuilding as well and didn't encounter any problems.  I'll close the comment, but please do follow up if you encounter any more trouble.
