### ISSUE TITLE
Inconsistency in hybrid signature algorithm names

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssl#124]
In the C source code e.g. https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/crypto/objects/obj_dat.h#L5798 hybrid signature algorithms have an underscore e.g. `p256_oqsdefault`.

But in the test harness https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs_test/tests/test_openssl.py#L23 and in README.md, the hybrid signature algorithms have a hyphen e.g. `p256-oqsdefault`.

Does this mean that they are not running correctly?

Observed by Michael Baentsch.

**Comment by zrlmib** [comment]
FWIW, additional comment: This becomes visible when changing line 76 in https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs_test/tests/test_openssl.py 
from
`else: sig_alg_sized = "rsa"`
 to read 
`else: sig_alg_sized = sig_alg`
(which arguably is better as then sig algs other than ECDSA and RSA get tested).

**Comment by xvzcf** [comment]
Indeed, the hybrid signature algorithms were not being tested. [This](https://github.com/open-quantum-safe/openssl/pull/125) should fix it.
