### ISSUE TITLE
testing PQ enabled openssl with s_time cmd

### ISSUE THREAD

**Issue by RicardoGaGu** [open-quantum-safe/openssl#137]
Hi! I'm considering doing a little benchmark of the post quantum ciphers in a openssl playground (mainly kex & signature algorithms). I've tested the command line server that comes with the openssl server and generated a self signed certificate with the pq signature of choice. I could connect to this server via the  openssl s_client tool, which lets you specify with the -curves parameter the <KEX> algorithm. This option is not available with the s_time command, very handy when benchmarking TLS connections. How do I specifically force a KEX algorithm in the test server/client connection with s_time. Are there any workarounds that you might know?

Thank you!

**Comment by baentsch** [comment]
The `-curves` parameter is available with the openssl `s_server` command, so why not use that to drive the test?

For example, this command pair performs a KEM=kyber512 perf test: 
```
openssl s_server -key conf/server.key -cert conf/server.crt -www -curves kyber512 & 
openssl s_time
```

OK, you have to start the server with another KEM each time, but it's a quick workaround.

**Comment by baentsch** [comment]
Available via [this](https://github.com/open-quantum-safe/openssl#performance-testing) (PR #155) and [this](https://github.com/open-quantum-safe/oqs-demos/tree/master/curl#performance-testing)
