### ISSUE TITLE
Kyber algorithms not found

### ISSUE THREAD

**Issue by RLuuPOC** [open-quantum-safe/openssl#153]
Hi,
I am new to OQS Openssl but I did use Openssl (release ver. 1.1.1d) to generate out public and private keys with RSA and encrypt/decrypt file with AES-CBC. I tried to use quantum resistance key encapsulation mechanism through Kyber and signature schemes with Dilithium for my project. 
I followed instruction to build openssl with libops and the build seemed OK (version 1.1.1d with many warning in libops library). I got "Algorithm kyber512 not found" error message when generated private key using "genpkey" command.  See attached screen capture.  
Below is the steps I used on my computer, ubuntu 18.04.
1. sudo apt install cmake gcc libtool libssl-dev make ninja-build unzip xsltproc
2.  git clone --branch OQS-OpenSSL_1_1_1-stable https://github.com/open-quantum-safe/openssl.git Qopenssl
3. git clone --branch master https://github.com/open-quantum-safe/liboqs.git
cd liboqs
mkdir build && cd build
cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/test/Qopenssl/oqs ..
ninja
ninja install
4.  ./Configure no-shared linux-x86_64 -lm
make -j

Please assist.
Thanks,
Raymond 
![Kyber512-not-found](https://user-images.githubusercontent.com/47870738/75815219-dffa3780-5d47-11ea-8542-49a003b2644f.png)

**Comment by dstebila** [comment]
Post-quantum KEMs are only available within TLS 1.3, they are not available to use directly as a public key encryption mechanism in the command-line tools or API.  This is related to the long-standing open issue #59.

**Comment by RLuuPOC** [comment]
Hi Douglas,
I even tried simple commands from TLS demo section (Readme.md) but they did not even recognize Kyber512 algo.

1.  ./apps/openssl req -x509 -new -newkey kyber512 -keyout kyber512_CA.key -out kyber512_CA.crt 
2.  ./apps/openssl genpkey -algorithm kyber512 -out kyber512_srv.key

Your response stated that kyber algo is not available through command-line tool such as openssl.  So, the above two command lines will NOT work.  Please confirm/clarify.

My objective is to demonstrate that I can generate out public and private keys from quantum resistance algorithm such as Kyber for my project.  This seems like not feasible through OQS using openssl.

Please response.
Thanks,
Raymond

**Comment by dstebila** [comment]
You are confusing KEMs and signature schemes.  X509 certificates are about signature schemes.  Kyber is a KEM.

**Comment by ReverseControl** [comment]
@RLuuPOC The Crystal Kyber proposal is used for both a KEM scheme and a signature scheme; take a look at the Crystal-Kyber in the arxiv as well as the NIST submission paper on Crystal-Kyber [ [https://pq-crystals.org/](https://pq-crystals.org) ]. The KEM is widely refered to as "kyber" although the ``dilithium`` set of signatures are also based on the Crystal-Kyber Mathematical construction as well; it is just not obvious from the name.

As for the instructions, they do work. I have tested them, for the Crystal-Kyber based signature scheme just give it the right name and it will generate them:

```
./apps/openssl req -x509 -new -newkey dilithium2 -keyout d2_CA.key -out d2_CA.crt
./apps/openssl req -x509 -new -newkey dilithium3 -keyout d3_CA.key -out d3_CA.crt
./apps/openssl req -x509 -new -newkey dilithium4 -keyout d4_CA.key -out d4_CA.crt
```

**Comment by baentsch** [comment]
@RLuuPOC @ReverseControl [This](https://github.com/open-quantum-safe/openssl#supported-algorithms) defines KEM+SIGs for OQS-openssl. "[Crystals](https://pq-crystals.org/)" is the "family name" for

> Kyber, an IND-CCA2-secure key-encapsulation mechanism (KEM); and Dilithium, a strongly EUF-CMA-secure digital signature algorithm

**Comment by RLuuPOC** [comment]
Hi,
For Kyber (used for KEM), I tried to use "openssl genpkey" command to generate the private/public key but got an error message, "Algorithm kyber512 not found".  
./apps/openssl genpkey -algorithm kyber512 -out kyber512_srv.key

Is this correct syntax to generate out private key?
Thanks,
Raymond
