### ISSUE TITLE
Reduce number of default KEX algorithms

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssl#162]
Having a large number of default KEX algorithms is causing problems in software that expects a shorter list.  We should reduce the list of default KEX algorithms in TLS 1.3 to just the level 1 hybrids.

**Comment by baentsch** [comment]
See my comment on the PR: I'd think we should not limit OQS-openssl _this_ heavily. I'd think there is a way to keep supporting all algorithms that work OK in liboqs (splitting+run-time activating by NIST levels, splitting by  algorithm families, or any other idea to whittle down the list such as to not "overwhelm" downstream apps with an overly long list of "curves"/PQC algs).
