### ISSUE TITLE
Change hybrid curve numbers to use private range as recommended in Internet-Draft

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssl#168]
https://tools.ietf.org/html/draft-stebila-tls-hybrid-design-03 says the code points reserved for hybrid private use are `0x2F00..0x2FFF`, so we should use that range.

**Comment by christianpaquin** [comment]
We don't have hard dependencies on the currently implemented code points, so it should be ok to modify them. What about non-hybrid algorithms?

**Comment by dstebila** [comment]
We would leave those in the current private range; the Internet-Draft doesn't speak to PQ-only KEX methods.
