### ISSUE TITLE
Installation/Configuration Problem

### ISSUE THREAD

**Issue by Richardo4039** [open-quantum-safe/openssl#182]
Hello,

First of all, im sorry for my bad english

I got this problem when i want to configure openssl oqs into my VirtualBox Linux Ubuntu 18.04, it said that the file include/openssl/evp.h cant read "include <oqs.oqs.h>", it happen in "make -j" command

And also, before the "make -j" command, i run the "cmake -GNinja -DCMAKE_INSTALL_PREFIX=<OPENSSL_DIR>=oqs .." some error said that "Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)" Does this has the connection problem with the oqs folder?

Here is the detail of errors

```
In file included from include/openssl/x509.h:18:0,
                 from apps/apps.h:26,
                 from apps/app_rand.c:10:
include/openssl/evp.h:18:11: fatal error: oqs/oqs.h: No such file or directory
 # include <oqs/oqs.h>
           ^~~~~~~~~~~
compilation terminated.
In file included from include/openssl/x509.h:18:0,
                 from apps/apps.h:26,
                 from apps/s_cb.c:14:
include/openssl/evp.h:18:11: fatal error: oqs/oqs.h: No such file or directory
 # include <oqs/oqs.h>
           ^~~~~~~~~~~
In file included from include/openssl/x509.h:18:0,
                 from apps/apps.h:26,
                 from apps/opt.c:9:
include/openssl/evp.h:18:11: fatal error: oqs/oqs.h: No such file or directory
 # include <oqs/oqs.h>
           ^~~~~~~~~~~
compilation terminated.
```

Thank you for your amazing work.

**Comment by baentsch** [comment]
@Richardo4039 Thanks for your interest in OQS. When looking at your command above 

> "cmake -GNinja -DCMAKE_INSTALL_PREFIX=<OPENSSL_DIR>=oqs .."

is it possible that you did not replace '<OPENSSL_DIR>' with the full path to the actual folder where you are building openssl? The real command should look something like 

`cmake -GNinja -DCMAKE_INSTALL_PREFIX=/opt/openssl-src/oqs ..`

(replacing "/opt/openssl-src/oqs" with the actual folder you're working in). Also, there clearly is one "=" sign too many).

The Doxygen error means that you have not installed doxygen on your Ubuntu. But this seems like a secondary issue.

**Comment by Richardo4039** [comment]
Im sorry, i made a typo with the "=" when i upload this issue.

for the `cmake -GNinja -DCMAKE_INSTALL_PREFIX=<OPENSSL_DIR>/oqs ..` command, i already change the OPENSSL_DIR into my own directory, like 
`cmake -GNinja -DCMAKE_INSTALL_PREFIX=PA/oqs ..` 

i saved liboqs folder and my openssl-dir (PA) in same folder, it is not a problem if i saved these 2 folders in the same place, right? Or i have to saved these 2 folders in some specific folder? I didnt find that i have to clone these 2 folders in specific folders in QuicStart guide.

Ow, alright then, i thought Doxygen is already included from this repository. 'Cause i started to learn oqs a month ago, forgive my ignorance..

**Comment by baentsch** [comment]
You can `git clone` the two folders of liboqs and openssl wherever you like. But the `CMAKE_INSTALL_PREFIX` path above _must_ point to the location where you downloaded openssl to (probably ending in '.../openssl/oqs'). The path 'PA' doesn't look right. Best have a full path there.

**Comment by Richardo4039** [comment]
Oops, okay, got it, it work, thanks a lot for your explanation and help!
