### ISSUE TITLE
Integrate all of OQS algorithms

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssl#194]
Make sure all of OQS's algs are available in OpenSSL.

(I'll start on that, @dstebila)

**Comment by christianpaquin** [comment]
@dstebila, what's the process of adding new algs to the [TLS 1.3 PQ and hybrid groups](https://docs.google.com/spreadsheets/d/12YarzaNv3XQNLnvDsWLlRKwtZFhRrDdWf36YlzwrPeg/edit?usp=sharing) spreadsheet? We're missing Classic-McEliece.

**Comment by dstebila** [comment]
> @dstebila, what's the process of adding new algs to the [TLS 1.3 PQ and hybrid groups](https://docs.google.com/spreadsheets/d/12YarzaNv3XQNLnvDsWLlRKwtZFhRrDdWf36YlzwrPeg/edit?usp=sharing) spreadsheet? We're missing Classic-McEliece.

I sent you an invitation to edit the spreadsheet. Go ahead and add the ones you need, sequentially after the existing ones.

**Comment by dstebila** [comment]
Is this done now?

**Comment by xvzcf** [comment]
Not yet. It will be when https://github.com/open-quantum-safe/openssl/tree/more-sig-algs is merged into master, but that is pending a decision on what signature algorithms to enable by default.

**Comment by xvzcf** [comment]
Fixed by https://github.com/open-quantum-safe/openssl/pull/213
