### ISSUE TITLE
Algorithm identifiers

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/openssl#209]
Hello, this is a question. I was going through the OpenSSL code and I just wanted to know where or what the Post Quantum signature algorithm identifiers are. For example, TLS 1.3 algorithm identifiers(shown in image TLS 1.3 sig image) and the hybrid key exchange identifiers (shown in KEM image) in s_cb.c but I was not able to find where the post-quantum signature algorithms identifiers are.

![TLS 1 3 sig](https://user-images.githubusercontent.com/54725951/84188444-d708b880-aa50-11ea-8f5b-be849e789860.PNG)
![KEM](https://user-images.githubusercontent.com/54725951/84188449-d839e580-aa50-11ea-8edb-b0b5c32062f5.PNG)

**Comment by baentsch** [comment]
@prchander The current list (of OQS-signature NIDs) is [here](https://github.com/open-quantum-safe/openssl/blob/749d194240f415cd4a3dbbf13c5d177dbfdb304c/crypto/ec/oqs_meth.c#L76). You can convert those to strings using `OBJ_nid2sn`. For an example, see the [OQSSIG_options method](https://github.com/open-quantum-safe/openssl/blob/749d194240f415cd4a3dbbf13c5d177dbfdb304c/crypto/ec/oqs_meth.c#L525) -- which actually delivers the list you're looking for when running `openssl speed x`.

**Comment by prchander** [comment]
@baentsch Thank you so much.

**Comment by baentsch** [comment]
You're welcome. Closing the issue then.
