### ISSUE TITLE
Update OpenSSL build instructions on Windows to refer to CMake

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssl#210]
https://github.com/open-quantum-safe/openssl#windows still refers to msbuild and the Visual Studio solution.

**Comment by christianpaquin** [comment]
I've noticed that the OQS windows build instructions are very minimal; didn't work for me. Quite late to check that, I know, but can you give me tomorrow to test that before tagging the OQS release, @dstebila ?

**Comment by dstebila** [comment]
I've already tagged the liboqs release. But if you want to change them I don't mind retagging due to a documentation change.

**Comment by christianpaquin** [comment]
> I've already tagged the liboqs release. But if you want to change them I don't mind retagging due to a documentation change.

Ah, I missed that. I got liboqs to compile on windows, but using Ninja (vs. VS like in the early cmake days). I'll document the full procedure on the openssl side; should be sufficient for now. I also got the s_server/s_client test to work, so this should be a simple doc fix.

**Comment by dstebila** [comment]
Fixed by #211.
