### ISSUE TITLE
Openssl fails to build with liboqs on Ubuntu 18.04

### ISSUE THREAD

**Issue by kaiduanx** [open-quantum-safe/openssl#218]
I followed the instructions to build liboqs and openss on Ubuntu18.04.4

b43s@ASUS-B43S:~/openquantumsafe$ ls
liboqs  openssl

liboqs is installed in openssl/oqs

b43s@ASUS-B43S:~/openquantumsafe/openssl$ ls oqs
include  lib

However the build failed with above error (I only paste some part of the error)

/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:7024: recipe for target 'test/asn1_string_table_test' failed
make[1]: *** [test/asn1_string_table_test] Error 1
/usr/bin/ld: error: ./libcrypto.a(x509_vfy.o)(.text) is too large (0x4ff8 bytes)
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:7123: recipe for target 'test/bio_enc_test' failed
make[1]: *** [test/bio_enc_test] Error 1
/usr/bin/ld: error: oqs/lib/liboqs.a(poly.c.o)(.text.PQCLEAN_KYBER768_CLEAN_poly_tomsg) is too large (0x2557 bytes)
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:7050: recipe for target 'test/asynciotest' failed
make[1]: *** [test/asynciotest] Error 1
/usr/bin/ld: error: oqs/lib/liboqs.a(parallel_matrix_op.c.o)(.text.PQCLEAN_RAINBOWIIICCYCLIC_CLEAN_batch_mat_madd_gf256) is too large (0x131 bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(blas.c.o)(.text.PQCLEAN_RAINBOWIIICCYCLICCOMPRESSED_CLEAN_gf256v_mul_scalar) is too large (0x3a bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(blas_comm.c.o)(.text.gf256mat_gauss_elim_ref) is too large (0x1ae bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(gf.c.o)(.text.PQCLEAN_RAINBOWIIICCYCLICCOMPRESSED_CLEAN_gf256_inv) is too large (0x5e5 bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(parallel_matrix_op.c.o)(.text.PQCLEAN_RAINBOWIIICCYCLICCOMPRESSED_CLEAN_UpperTrianglize) is too large (0x111 bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(blas.c.o)(.text.PQCLEAN_RAINBOWVCCLASSIC_CLEAN_gf256v_mul_scalar) is too large (0x3a bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(blas_comm.c.o)(.text.gf256mat_gauss_elim_ref) is too large (0x1ae bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(gf.c.o)(.text.PQCLEAN_RAINBOWVCCLASSIC_CLEAN_gf256_inv) is too large (0x5e5 bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(parallel_matrix_op.c.o)(.text.PQCLEAN_RAINBOWVCCLASSIC_CLEAN_UpperTrianglize) is too large (0x111 bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(blas.c.o)(.text.PQCLEAN_RAINBOWVCCYCLIC_CLEAN_gf256v_mul_scalar) is too large (0x3a bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(blas_comm.c.o)(.text.gf256mat_gauss_elim_ref) is too large (0x1ae bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(gf.c.o)(.text.PQCLEAN_RAINBOWVCCYCLIC_CLEAN_gf256_inv) is too large (0x5e5 bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(parallel_matrix_op.c.o)(.text.PQCLEAN_RAINBOWVCCYCLIC_CLEAN_UpperTrianglize) is too large (0x111 bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(blas.c.o)(.text.PQCLEAN_RAINBOWVCCYCLICCOMPRESSED_CLEAN_gf256v_mul_scalar) is too large (0x3a bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(blas_comm.c.o)(.text.gf256mat_gauss_elim_ref) is too large (0x1ae bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(gf.c.o)(.text.PQCLEAN_RAINBOWVCCYCLICCOMPRESSED_CLEAN_gf256_inv) is too large (0x5e5 bytes)
/usr/bin/ld: error: oqs/lib/liboqs.a(parallel_matrix_op.c.o)(.text.PQCLEAN_RAINBOWVCCYCLICCOMPRESSED_CLEAN_UpperTrianglize) is too large (0x111 bytes)
/usr/bin/ld: error: /usr/lib/gcc/x86_64-linux-gnu/7/libgcc.a(_popcountsi2.o)(.eh_frame) is too large (0x30 bytes)
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:6829: recipe for target 'fuzz/asn1parse-test' failed
make[1]: *** [fuzz/asn1parse-test] Error 1
/usr/bin/ld: error: oqs/lib/liboqs.a(frodo1344shake.c.o)(.text.OQS_KEM_frodokem_1344_shake_decaps) is too large (0x18ba bytes)
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:6881: recipe for target 'fuzz/cms-test' failed
make[1]: *** [fuzz/cms-test] Error 1
/usr/bin/ld: error: oqs/lib/liboqs.a(haraka.c.o)(.text.PQCLEAN_SPHINCSHARAKA256SROBUST_CLEAN_haraka512_perm) is too large (0x1213 bytes)
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
Makefile:7136: recipe for target 'test/bio_memleak_test' failed
make[1]: *** [test/bio_memleak_test] Error 1
make[1]: Leaving directory '/home/b43s/openquantumsafe/openssl'
Makefile:174: recipe for target 'all' failed
make: *** [all] Error 2
b43s@ASUS-B43S:~/openquantumsafe/openssl$ 

Any idea on what is wrong?

/Kaiduan

**Comment by baentsch** [comment]
@kaiduanx Not really: I personally never saw something like this - our CI system indeed does such builds _very_ regularly on Ubuntu 18.04, this also ran OK tonight. Also my default personal build system is Ubuntu 18.04.4.

To try to close in on this, can you please share the build options used when building liboqs and openssl, respectively? Can you confirm you're running an Ubuntu 18 stock gcc 7.5.0 (`gcc --version`)? 

Last question: Can you please share/compare the compile commands that actually created this output? I just checked on our side and all targets failing in the above build OK for me like this:
```
${LDCMD:-gcc} -pthread -m64 -Ioqs/include -Wall -O3 -L. -Loqs/lib  \
        -o test/bio_enc_test test/bio_enc_test.o \
         test/libtestutil.a -lcrypto -ldl -pthread -loqs -lm
gcc  -Iinclude -pthread -m64 -Ioqs/include -Wall -O3 -DNDEBUG  -MMD -MF test/bio_memleak_test.d.tmp -MT test/bio_memleak_test.o -c -o test/bio_memleak_test.o test/bio_memleak_test.c
[...]
${LDCMD:-gcc} -pthread -m64 -Ioqs/include -Wall -O3 -L. -Loqs/lib  \
        -o fuzz/asn1parse-test fuzz/asn1parse.o fuzz/test-corpus.o \
         -lcrypto -ldl -pthread -loqs -lm
```

**Comment by kaiduanx** [comment]
My gcc version is 7.5.0

b43s@ASUS-B43S:~/openquantumsafe/openssl$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

if I rerun the command again make -j after failure, the build succeeded!

**Comment by baentsch** [comment]
> if I rerun the command again make -j after failure, the build succeeded!

OK, then this may have to do with resource exhaustion on your machine during build. To check this as cause for this issue, what about running `make clean && make` (without `-j`) again to see whether this way everything builds OK? If it fails, please provide the full gcc command that triggered the failure(s).

**Comment by kaiduanx** [comment]
Thanks @baentsch , make clean & make work without issue at all.

**Comment by baentsch** [comment]
@kaiduanx Thanks for this confirmation. I'd then suggest to close this issue. Please re-open with additional details to reproduce if the problem "comes back".
