### ISSUE TITLE
sidhp751 causes openvpn crashes - possibly due to oqs-openssl

### ISSUE THREAD

**Issue by pqfan** [open-quantum-safe/openssl#235]
Greetings,

Since a while ago, I would like to report that oqs-openssl seems to crash when sidhp751 is used as KEM. This occurs when you use the Microsoft's PQCrypto-VPN built with liboqs and openssl-oqs latest releases (after cross-compiling for windows aswell - the crash happens in the linux built as I have observed)

**Comment by christianpaquin** [comment]
> Since a while ago, I would like to report that oqs-openssl seems to crash when sidhp751 is used as KEM.

@pqfan, could you provide some repro information? Which version (commit) did you sync with? What build steps did you do? Which platform versions are you using? Thanks!

**Comment by pqfan** [comment]
@christianpaquin This started to occur since liboqs 0.3.0 and openssl-oqs of that according version if I remember well. There is already a release of the PQCrypto-VPN where you can test this and possibly detect the same error as me (except the case my error is hardware related or something) from [here](https://github.com/microsoft/pqcrypto-vpn) or can be reviewed directly from [Microsoft's OpenVPN build system](https://github.com/microsoft/openvpn-build) which is the same engine I use to build the final custom version of PQCrypto-VPN. I am running on Windows 10 and running/building/cross-compiling on Ubuntu 18.04.

Thanks a lot for your time and project work so far Christian!

**Comment by christianpaquin** [comment]
sidhp751 passes in our openssl tests. This could be an issue that only surfaces in OpenVPN; I suggest you open an issue [there](https://github.com/microsoft/PQCrypto-VPN) instead.

**Comment by pqfan** [comment]
I thought that the failure could be due to some openssl crash, but maybe you are right since tests are checked on compile/build time e.t.c.
Will check with PQCrypto-VPN then, some implementation failure or openvpn protocol mismatch and so...
Closing this issue, thanks again.
