### ISSUE TITLE
Add CI tests on Windows

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssl#236]
Add CI tests on Windows

**Comment by xvzcf** [comment]
Just noting down so I don't forget: The project already has an `appveyor.yml` that runs a bunch of Windows tests. These tests don't work in our fork, and we have to figure out why.

**Comment by christianpaquin** [comment]
> Just noting down so I don't forget: The project already has an `appveyor.yml` that runs a bunch of Windows tests. These tests don't work in our fork, and we have to figure out why.

Yes, because our fork as a bunch of OQS stuff that doesn't compile. My strategy in PR #237 was to keep the original appveyor config as close to the original as possible, adding the OQS build, and our PQ tests, keeping the other tests as well.

**Comment by baentsch** [comment]
Finally managed to get an [AppVeyor job through](https://ci.appveyor.com/project/dstebila/openssl/builds/39075748) to build and test liboqs and oqs-openssl; openssl tests all pass but `oqs-test/test_tls_basic.py` fails on these algs:
```

=============================================== short test summary info ===============================================
FAILED oqs-test\test_tls_basic.py::test_kem[bike1l1cpa] - AssertionError: Got unexpected return code 1
FAILED oqs-test\test_tls_basic.py::test_kem[bike1l3cpa] - AssertionError: Got unexpected return code 1
FAILED oqs-test\test_tls_basic.py::test_kem[bike1l1fo] - AssertionError: Got unexpected return code 1
FAILED oqs-test\test_tls_basic.py::test_kem[bike1l3fo] - AssertionError: Got unexpected return code 1
FAILED oqs-test\test_tls_basic.py::test_kem[p256_bike1l1cpa] - AssertionError: Got unexpected return code 1
FAILED oqs-test\test_tls_basic.py::test_kem[p384_bike1l3cpa] - AssertionError: Got unexpected return code 1
FAILED oqs-test\test_tls_basic.py::test_kem[p256_bike1l1fo] - AssertionError: Got unexpected return code 1
FAILED oqs-test\test_tls_basic.py::test_kem[p384_bike1l3fo] - AssertionError: Got unexpected return code 1
ERROR oqs-test\test_tls_basic.py::test_sig[rainbowVclassic] - AssertionError: Got unexpected return code 3221225725
ERROR oqs-test\test_tls_basic.py::test_sig[p521_rainbowVclassic] - AssertionError: Got unexpected return code 3221225725
================================= 8 failed, 116 passed, 2 errors in 442.06s (0:07:22) =================================
```
--> Bike seems to be "expected" as per [this](https://github.com/open-quantum-safe/liboqs/blob/1b25f45f352122d4e4c00bddac4ec5f5b649dd2b/.CMake/alg_support.cmake#L30-L31); is the RainbowVclassic failure also expected? If so, I'd then disable both for Win32 in the PR to close this issue.

Second issue: When executing all oqs-tests, this error message appeared:

> Build execution time has reached the maximum allowed time for your plan (60 minutes).

--> Any objections to only run the basic TLS connection requests on Windows? Or shall we change to another plan to do full testing? 

Tagging @dstebila @christianpaquin @xvzcf

**Comment by christianpaquin** [comment]
> --> Any objections to only run the basic TLS connection requests on Windows? Or shall we change to another plan to do full testing?

No objections from me.
