### ISSUE TITLE
MAX_CURVELIST too small

### ISSUE THREAD

**Issue by crest42** [open-quantum-safe/openssl#238]
Hi,

first, thank you all for the amazing work. While building up a freeradiusd with the 1.1.1 branch of this fork, i encountered a problem when using rather long curves_list. It turns out the maximum amount of curves in a list is defined in ssl/t1_lib.c as:

`# define MAX_CURVELIST   OSSL_NELEM(nid_list)`

`nid_list` only includes ecdc curves, while the pq algos and hybrid implementations are defined in `oqs_nid_list` and `oqs_hybrid_nid_list`. When using more curves than member in `nid_list`, the curve list evaluation function fails silently.

This small fix works for me:

`# define MAX_CURVELIST   (OSSL_NELEM(nid_list)+OSSL_NELEM(oqs_nid_list)+OSSL_NELEM(oqs_hybrid_nid_list))`

If you have no objections against this change, i can send a PR.

Regards,
Robin

**Comment by christianpaquin** [comment]
Yes, please send a PR, it will trigger our tests and make it easier to review the fix. Thanks!
