### ISSUE TITLE
openssl rsa noout 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/openssl#246]
I need to remove the dots that are printed when generating RSA keys. where should I use the -noout command in the command below?
apps/openssl genpkey -algorithm rsa -out /home/pi/openssl/CA-project/csr/key_srv.key -noout -pkeyopt rsa_keygen_bits:2048

**Comment by baentsch** [comment]
Hmm -- generating classic crypto keys (RSA in this case) is not code that OQS changed; thus, this is a question for upstream OpenSSL.

**Comment by baentsch** [comment]
@prchander Is there an update from your side as to why you think this is an OQS issue? We'll otherwise close this.

**Comment by prchander** [comment]
@baentsch I reached out to upstream OpenSSL and it looks like the dots and pluses cannot be hidden. I do not think it is an issue but it would be very nice to have an option to remove them to get accurate results of key and signature generation.

**Comment by baentsch** [comment]
@prchander Do you think these outputs materially change the accuracy of keygen? I can't really imagine -- and that's probably the reason why the openssl team also leaves this in. So we also close this here -- also as we don't want to modify "classic" crypto code in our project.
