### ISSUE TITLE
no documentation for "it might still be possible to use it in the fork through either one of two ways" 

### ISSUE THREAD

**Issue by frankimhof** [open-quantum-safe/openssl#253]
## Description
I wanted to know how to use supported algorithms (mc_eliece for example) that are not listed.
You write on the main page, that "it might still be possible to use it in the fork through [**either one of two ways**](https://github.com/open-quantum-safe/openssl/wiki/Using-liboqs-algorithms-that-are-not-in-the-forks
)", but the link leads to an empty page.

Thanks in advance.

**Comment by xvzcf** [comment]
The link is [here](https://github.com/open-quantum-safe/openssl/wiki/Using-liboqs-algorithms-not-in-the-fork). It seems there's a slight typo in the README.

**Comment by frankimhof** [comment]
Perfect, thank you
