### ISSUE TITLE
liboqs generation meets source code error

### ISSUE THREAD

**Issue by sjf-tjdg** [open-quantum-safe/openssl#269]
[Makefile:3139: crypto/ec/oqs_meth.o] Error 1

When I tried to install liboqs and build teh fork to my openssl(version 1.1.1f), the error jumped out.
The steps is followed by ubantu parts on https://github.com/prchander/openssl#supported-algorithms.

It looks like this
crypto/ec/oqs_meth.c:222:14: error: 'OQS_SIG_alg_rainbow_I_classic' undeclared (first use in this function); did you mean 'OQS_SIG_alg_rainbow_Ia_classic'?
  222 |       return OQS_SIG_alg_rainbow_I_classic;
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              OQS_SIG_alg_rainbow_Ia_classic
crypto/ec/oqs_meth.c:222:14: note: each undeclared identifier is reported only once for each function it appears in
crypto/ec/oqs_meth.c:225:14: error: 'OQS_SIG_alg_rainbow_V_classic' undeclared (first use in this function); did you mean 'OQS_SIG_alg_rainbow_Vc_classic'?
  225 |       return OQS_SIG_alg_rainbow_V_classic;
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |              OQS_SIG_alg_rainbow_Vc_classic
crypto/ec/oqs_meth.c:335:14: error: 'OQS_KEM_alg_hqc_128' undeclared (first use in this function); did you mean 'OQS_KEM_alg_count'?
  335 |       return OQS_KEM_alg_hqc_128;
      |              ^~~~~~~~~~~~~~~~~~~
      |              OQS_KEM_alg_count
crypto/ec/oqs_meth.c:338:14: error: 'OQS_KEM_alg_hqc_192' undeclared (first use in this function); did you mean 'OQS_KEM_alg_count'?
  338 |       return OQS_KEM_alg_hqc_192;
      |              ^~~~~~~~~~~~~~~~~~~
      |              OQS_KEM_alg_count
crypto/ec/oqs_meth.c:341:14: error: 'OQS_KEM_alg_hqc_256' undeclared (first use in this function); did you mean 'OQS_KEM_alg_count'?
  341 |       return OQS_KEM_alg_hqc_256;
      |              ^~~~~~~~~~~~~~~~~~~
      |              OQS_KEM_alg_count
make[1]: *** [Makefile:3139: crypto/ec/oqs_meth.o] Error 1
make[1]: Leaving directory '/home/sjf20/openssl'
make: *** [Makefile:174：all] 错误 2

**Comment by baentsch** [comment]
Your `liboqs` and `openssl` projects do not seem to be in sync: We recently changed the Rainbow algorithm family which necessitated changes (to exactly the constants showing up above) in both repositories. Be sure to pull those over to your fork.

**Comment by sjf-tjdg** [comment]
> Your `liboqs` and `openssl` projects do not seem to be in sync: We recently changed the Rainbow algorithm family which necessitated changes (to exactly the constants showing up above) in both repositories. Be sure to pull those over to your fork.

Thank you for replying. Does it mean I need to get the newest 'liboqs git' for the project, and repeat the following steps of install liboqs?

**Comment by baentsch** [comment]
That -- and ensure that your own oqs-openssl fork has the most recent updates from open-quantum-safe/openssl.

**Comment by baentsch** [comment]
Closing after more than a week inactivity.
