### ISSUE TITLE
Current master out of sync with the current liboqs

### ISSUE THREAD

**Issue by mouse07410** [open-quantum-safe/openssl#276]
In the NIST PQC round 3, and in the current https://github.com/open-quantum-safe/liboqs, Dilithium-4 has been dropped, and replaced with Dilithium-5.

This package now fails to compile, and will keep failing until it's brought in sync withi this Dilithium change.

**Comment by baentsch** [comment]
ACK. Dil*-AES variants got added, too. Working on it.

**Comment by baentsch** [comment]
Closed via #277
