### ISSUE TITLE
Dilithium family not enabled. 

### ISSUE THREAD

**Issue by prchander** [open-quantum-safe/openssl#285]
I brought us this issue in #282 thinking it was related but I am just going to open another one. 

None of the Dilithium family works for me and I have tried reinstalling liboqs and openssl. I have also checked generate.ylm and Dilithium looks to be enabled.
apps/openssl genpkey -algorithm dilithium2 -out dilithium2_srv.key
Warning: OQS algorithm 'Dilithium2' not enabled.
Error generating key
140391613919552:error:101280A5:elliptic curve routines:oqs_key_init:no such oqs algorithm:crypto/ec/oqs_meth.c:785:
140391613919552:error:10132040:elliptic curve routines:pkey_oqs_keygen:fatal:crypto/ec/oqs_meth.c:1401:
However Falcon works

**Comment by baentsch** [comment]
Can I ask the exact sequence of (build) commands you executed to arrive at this? What's the contents  of `oqs/include/oqs/oqsconfig.h` (first 7 lines and the lines dealing with Dilithium)?

**Comment by baentsch** [comment]
Can I ask the exact sequence of (build) commands you executed to arrive at this? What's the contents  of `oqs/include/oqs/oqsconfig.h` (first 7 lines and the lines dealing with Dilithium)?

**Comment by prchander** [comment]
// SPDX-License-Identifier: MIT

#define OQS_VERSION_TEXT "0.5.0-dev"
#define OQS_COMPILE_BUILD_TARGET "x86_64-Linux-4.15.0-135-generic"
#define OQS_PORTABLE_BUILD 1

#define OQS_KEM_DEFAULT OQS_KEM_alg_frodokem_640_aes
#define OQS_SIG_DEFAULT OQS_SIG_alg_dilithium_2

#define OQS_ENABLE_SIG_DILITHIUM 1
#define OQS_ENABLE_SIG_dilithium_2 1
#define OQS_ENABLE_SIG_dilithium_2_avx2 1
#define OQS_ENABLE_SIG_dilithium_3 1
#define OQS_ENABLE_SIG_dilithium_3_avx2 1
#define OQS_ENABLE_SIG_dilithium_5 1
#define OQS_ENABLE_SIG_dilithium_5_avx2 1
#define OQS_ENABLE_SIG_dilithium_2_aes 1
#define OQS_ENABLE_SIG_dilithium_2_aes_avx2 1
#define OQS_ENABLE_SIG_dilithium_3_aes 1
#define OQS_ENABLE_SIG_dilithium_3_aes_avx2 1
#define OQS_ENABLE_SIG_dilithium_5_aes 1
#define OQS_ENABLE_SIG_dilithium_5_aes_avx2 1

Steps I used to build: 
Git clone liboqs
git clone openssl

liboqs
cmake -GNinja -DBUILD_SHARED_LIBS=ON..
cmake -GNinja -DCMAKE_INSTALL_PREFIX=<OPENSSL_DIR>/oqs ..
ninja 
ninja install 

Openssl 
./Configure no-shared linux-x86_64 -lm
sudo make -j

**Comment by baentsch** [comment]
Strange - this all looks ok -- except the line `cmake -GNinja -DBUILD_SHARED_LIBS=ON..`: Why do you to this? You seem to want to run everything static. When I do all of the above (except the shared liboqs build) within docker image `openquantumsafe/ci-ubuntu-focal-x86_64`, everything builds OK and this runs fine as expected:
```
root@2b0a54afbd10:~/openssl# apps/openssl genpkey -algorithm dilithium2 -out dilithium2_srv.key
root@2b0a54afbd10:~/openssl# ls -l dilithium2_srv.key 
-rw------- 1 root root 5319 Feb 23 08:33 dilithium2_srv.key
```

**Comment by prchander** [comment]
@baentsch Thanks for your help. I guess I just wanted to be able to use it system wide. Removing that helped and all of Dilithium works now
