### ISSUE TITLE
KEMs, Hybrid KEMs and code points

### ISSUE THREAD

**Issue by bhess** [open-quantum-safe/openssl#296]
While working at adding hybrid KEMs to the OSSL3 provider, I ran into a few questions about the code points used for KEMs and hybrid KEMs in TLS. I open an issue here because it also affects interop with OSSL1.1.1.

- Interop with previous-round algorithms

Looking at the google sheets, some of the algorithm names still refer to round 2 variants:
https://docs.google.com/spreadsheets/d/12YarzaNv3XQNLnvDsWLlRKwtZFhRrDdWf36YlzwrPeg/edit#gid=0
In the meanwhile, the algorithms were updated to r3 while keeping the same code points. 
I imagine that this can cause confusion, similar to https://github.com/open-quantum-safe/liboqs/issues/909, when trying to interop between different libraries or between different versions of OQS.
Do we want to consider to update the code points after future algorithm updates?

- Hybrid KEM code points with ECX (X25519, X448)

I'm adding support for combining all OQS KEM with ECX and ECP curves in https://github.com/open-quantum-safe/oqs-provider/pull/16. The `generate.yml` file currently only defines code points for ECP-hybrids. Looking at https://tools.ietf.org/html/draft-ietf-tls-hybrid-design-01#section-3.1, the hybrid code points should fit in `0x2F00 .. 0x2FFF`. An option is to add the ECX-hybrids with a `0x40` offset to `0x2F..` (except for those three hybrid algorithms already defined with X25519). For example, a field in generate.yml would look like this:

```
    family: 'FrodoKEM'
    name_group: 'frodo640aes'
    nid: '0x0200'
    nid_hybrid: '0x2F00'
    nid_ecx_hybrid: '0x2F40'
    oqs_alg: 'OQS_KEM_alg_frodokem_640_aes'
    bit_security: 128
```
The OSSL3 provider currently imports generate.yml from the OSSL1.1.1 repository. If you agree, I'd open a PR here with new code points for ECX-hybrids (and the google sheets can be updated). OSSL1.1.1 doesn't necessarily need to support the additional ECX-hybrid code points.

- Strength matching X448

X448 with 224 bit security sits between NIST L3/L4 and L5. The initial attempt in https://github.com/open-quantum-safe/oqs-provider/pull/16 is to match PQC L3-L5 with X448, being aware that this is not an "exact" match. Are there any thoughts about this and if/how we should support hybrids with X448?

**Comment by baentsch** [comment]
> I'd open a PR here with new code points for ECX-hybrids (and the google sheets can be updated)

If I'm not entirely mistaken, the Google sheets are not maintained any more but `generate.yml` _is_ the documentation (right, @xvzcf ?)

> The OSSL3 provider currently imports generate.yml from the OSSL1.1.1 repository.

That was the easiest way to assure interop at the time. Before now moving logic that's only needed in oqsprovider into oqs-openssl, I'd ask the question whether we want to have those hybrids also in the OSSL111 fork? @dstebila @christianpaquin ? If not, wouldn't a patch-mechanism for `generate.yml` within oqsprovider only be more preferable (over moving this into oqs-openssl)?

**Comment by xvzcf** [comment]
> > I'd open a PR here with new code points for ECX-hybrids (and the google sheets can be updated)
> 
> If I'm not entirely mistaken, the Google sheets are not maintained any more but `generate.yml` _is_ the documentation (right, @xvzcf ?)
> 

Indeed, @bhess the new tables can be found [here (for KEMS)](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-kem-info.md) and [here (for signatures)](https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-sig-info.md). Once we have [YAML summaries of all the algorithms in liboqs](https://github.com/open-quantum-safe/liboqs/issues/892) I can add more information to these tables.

**Comment by bhess** [comment]
Thanks @baentsch and @xvzcf.

Regarding the ECX-hybrid code points: Since this is so far only supported in OSSL3-provider, I'm adding a separate .yml file there (with the new code points only).
Regarding X448: As discussed, we don't combine it with L5, only with L3/L4.
