### ISSUE TITLE
make install takes some errors

### ISSUE THREAD

**Issue by paulbruedgam** [open-quantum-safe/openssl#3]
Compiling OpenSSL with your instructions works very well, but when I started with "make install" after all other commands, I got some error.

**cp include/oqs/*.h /usr/local/ssl/include/oqs
cp: der Aufruf von stat für „include/oqs/kex_lwe_newhope.h“ ist nicht möglich: Datei oder Verzeichnis nicht gefunden
Makefile:551: recipe for target 'install_sw' failed
make: *** [install_sw] Error 1**

I tried it on Debian 8 with gcc (Debian 4.9.2-10) 4.9.2.

**Comment by dstebila** [comment]
Sorry about that.  I've fixed it now in commit 3392f4d53d7ba226683d452d575514690e473312.

**Comment by paulbruedgam** [comment]
Thanks. Now it work fine.
