### ISSUE TITLE
Update KEM and Signature information table once liboqs YAML docsheets are available.

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/openssl#307]
Add "NIST Round" and "Specification Version" fields to https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/generate-oid-nid-table.py once https://github.com/open-quantum-safe/liboqs/issues/892 is addressed.

**Comment by baentsch** [comment]
Maybe also automate platform-specific OSSL algorithm test inclusion/exclusions from the same YAML as/when available.

**Comment by baentsch** [comment]
@xvzcf Would you have time to do this? Currently this is blocking https://github.com/open-quantum-safe/oqs-demos/issues/83 -- which in turn is needed to generate a correct(ly documented) test server (which is due with the release of `liboqs v0.7.0`).

**Comment by xvzcf** [comment]
Would it also be worthwhile to add a "Specification Version" field?

**Comment by baentsch** [comment]
> Would it also be worthwhile to add a "Specification Version" field

Thought about it but didn't see enough of a difference to the current "Implementation Version" field.
