### ISSUE TITLE
[question] one certificate binding to multiple signature keys

### ISSUE THREAD

**Issue by zouhuan1215** [open-quantum-safe/openssl#317]
Say I have a server that has two types of signature key: one is an `RSA` key, the other is a `post-quantum-safe (pqs)` key. 
Is it possible to issue the server a certificate that bound to both the `RSA` key and `pqs` key?
Because with such certificate, a client supporting only RSA can verify the server certificate's RSA key, while a client supporting post-quantum can instead verify the server certificate's pqs key that is more secure. 

=============**some extra information related to this question**===============
1.  an ideal certificate binding to an `ECDSA` key and a `pqs` key might look like the following, where the `pqs` key is added to the `extension` filed (but I have no idea how to implement this with openSSL):
![image](https://user-images.githubusercontent.com/41979254/121152774-15a99c80-c878-11eb-8da3-8df5efd615de.png)

2.  [another solution: a with two certificates](https://security.stackexchange.com/questions/43360/is-possible-that-a-tls-server-send-more-than-one-certificate-to-the-client-for-t)--one certificate for the `RSA` key, and the other certificate for the `pqs` key

**Comment by baentsch** [comment]
I'd think this is mostly a question regarding standardization. See for example the discussion at #300 (and all links there). Please chime in there (and/or point to standards documents facilitating such multi-key certs if you are aware of such documents: The implementation would/should follow from there).

**Comment by zouhuan1215** [comment]
Thanks for your rely @baentsch. I've read your redirection links, and find this link---[State of Hybrid and Composite PQC in IETF Certificate Standards](https://docbox.etsi.org/Workshop/2019/201911_QSCWorkshop/TECHNICAL_TRACK/06_MIGRATION/ENTRUSTDATACARD_OUNSWORTH.pdf) particularly insightful and helpful. If there is any official document related to composite certs, I will post them in discussion #300.

**Comment by baentsch** [comment]
Discussion to be continued in #300 . New issue to be opened when implementation path is clear.
