### ISSUE TITLE
make test fails on OQS-OpenSSL_1_1_1-stable with OQS_DEFAULT_GROUPS set

### ISSUE THREAD

**Issue by AndyChung1997** [open-quantum-safe/openssl#323]
Hi, I followed the Quickstart to build OQS-OpenSSL_1_1_1-stable. When I built the OpenSSL, I got some error messages.
The following are my instructions:
```
sudo ./Configure shared linux-x86_64 -lm --prefix=/usr/local/ssl --openssldir=/usr/local/ssl -DOQS_DEFAULT_GROUPS=\"p256_kyber512:X25519:p256_hqc128\"
sudo make -j 4
sudo make test
```
There is no error in the first two instructions. But when I typed "sudo make test", I got some errors.

<img width="507" alt="123" src="https://user-images.githubusercontent.com/56081724/127129250-975b1605-aa84-4883-ad9f-fab74a443dae.PNG">
<img width="593" alt="456" src="https://user-images.githubusercontent.com/56081724/127129270-2be37428-8a3f-413d-8f7c-4012f2dc0e5e.PNG">

Is the setting of  `-DOQS_DEFAULT_GROUPS` wrong? Or is the algorithm not supported?

**Comment by baentsch** [comment]
Hmm -- no, the (default) algorithms (names) look OK. Does the same error happen in your environment when you build static? What if you build dynamic without setting `OQS_DEFAULT_GROUPS` (I'm not sure we tested the test suite when setting --other-- default groups)? What exactly _are_ the errors (running `make test V=1`)?
Edit: I can reproduce now -- so Thanks for the report -- will look into it.

**Comment by AndyChung1997** [comment]
>Does the same error happen in your environment when you build static? 

Yes, it also has the same error.
>What if you build dynamic without setting `OQS_DEFAULT_GROUPS`(I'm not sure we tested the test suite when setting --other-- default groups)?

No error occurred. All tests successful.

**Comment by baentsch** [comment]
@AndyChung1997 please check whether the issue is also gone for you and re-open this issue if NOK. Be sure to also enable ED448 for getting all classic alg tests to pass.
