### ISSUE TITLE
Demo of openssl speed test

### ISSUE THREAD

**Issue by AndyChung1997** [open-quantum-safe/openssl#332]
Recently I was testing the *openssl speed* command. I can’t understand why AES128-CBC can set `-bytes +int` option to run benchmarks on custom-sized buffer, but Bikel1 can’t set.

AES128-CBC:
![image](https://user-images.githubusercontent.com/56081724/133370419-bffa73c5-e095-42be-811b-598cb11e7f4e.png)
Bikel1:
![image](https://user-images.githubusercontent.com/56081724/133370540-88da3761-ff22-4902-bbcb-24ce736e373c.png)

**Comment by baentsch** [comment]
This option is for non-PKI/"streaming" crypto components. Please run `openssl speed -help`:

>  -bytes +int         Run [non-PKI] benchmarks on custom-sized buffer

And from https://www.openssl.org/docs/man1.1.1/man1/openssl-speed.html :

> -bytes num
>
>    Run benchmarks on num-byte buffers. Affects ciphers, digests and the CSPRNG.
