### ISSUE TITLE
Performance Testing 

### ISSUE THREAD

**Issue by hengyongming** [open-quantum-safe/openssl#335]
Hi,

Under the section for TLS end-to-end testing, the instructions only start a server and then measure the number of connections per time unit.

I am wondering if it is possible to start a client and server (both with their own certificate chain) together and then measure the connection time taken? Tried doing it but with no avail.

Thanks in advance !

**Comment by baentsch** [comment]
Hi - can you share what you tried and in which way things failed?

**Comment by hengyongming** [comment]
Hi i have solved this issue thanks !
