### ISSUE TITLE
How to build OQS OpenSSL on ARM Processor (Apple M1 Chip)

### ISSUE THREAD

**Issue by jingyosong** [open-quantum-safe/openssl#341]
I understood OQS OpenSSL library as the source code to build TLS 1.3 using PQC Cryptography. This Github presented how to build the OQS OpenSSL library in Mac, Linux, and Windows environments. Where Mac is a Mac with an Intel chip (x86). However, the build method for Mac with Apple-M1 chip is not provided, so I would like to ask if you can know how to build it. Thanks for reading this long article.

**Comment by baentsch** [comment]
Thanks for your interest in our work. May I ask whether you successfully built "stock"/upstream (non-QSC) OpenSSL on an M1? If so, which specific problems do you face building oqs-openssl? The core library `liboqs` should build OK on M1... But I have to admit I never tried building oqs-openssl on M1, so would need to look into it ... Any concrete issues you encountered could help me there.

**Comment by jingyosong** [comment]
The problem I was facing was with "Step 2: Build the fork" for building OpenSSL. The command ./Configure no-shared linux-x86_64 -lm (oR ./Configure no-shared darwin64-x86_64-cc) does not work in an M1-based macOS environment or an ARM-based Ubuntu environment. Is there a specific command to run this? Or is it a specific ARM architecture issue? Thanks for reading.

**Comment by baentsch** [comment]
I'd say the M1 should be "darwin64-arm64-cc"... And Yes, just confirmed: Everything then builds OK on an M1 box. Will update the documentation. Thanks for pointing out that omission.

**Comment by jingyosong** [comment]
In addition to Apple M1, I want to run OQS OpenSSL library in ARM-based Ubuntu environment. The ARM-based Ubuntu environment is a Jetson Xavier board and is equipped with ARMv8.2. As with Apple M1 error, to solve this problem, I tried the linux-arm64lip32 command considering Linux and ARMv8 in the Configure option, but it was confirmed that an error occurred during the Make -j option process and did not work. Considering the ARM-based Linux environment, I would like to know if there are specific instructions for building the fork. Thanks for reading this long article.

**Comment by baentsch** [comment]
> Considering the ARM-based Linux environment, I would like to know if there are specific instructions for building the fork. 

I'm afraid I don't have such environment at my disposal to check what error occurs, so please provide suitable logfile output to help me understand the issue.

**Comment by jingyosong** [comment]
Thank you for your reply. I want to build OQS OpenSSL on an ARMv8-based (64-bit) Ubuntu Linux environment in addition to Mac books with Apple M1 chip. So, I performed it according to the build method in Ubuntu Linux environment suggested on github (Step 0 - Step 2). Step 0 - 1 were completed without build error. In Step2, I tried to build by replacing the ./Configure no-shared linux-x86_64 -lm command with the ./Configure no-shared linux-aarch64 -lm command considering the ARMv8-based Ubuntu Linux environment, but the following error occurred. Is there a specific command to solve the error in Step 2 in ARMv8-based Ubuntu Linux environment? Thanks for reading this long post.

![Screenshot from 2021-12-06 10-34-42](https://user-images.githubusercontent.com/60771953/144773937-f2602906-c3a4-48d5-9336-3f1d3d6a7111.png)

**Comment by baentsch** [comment]
> Is there a specific command to solve the error in Step 2 in ARMv8-based Ubuntu Linux environment?

In one word: No. In more words --and please pardon me for the bluntness of those-- but did you read the error message at all? Your machine ran out of disk space.

**Comment by jingyosong** [comment]
I'm really sorry. thank you for the reply.
