### ISSUE TITLE
Supporting openssl dgst

### ISSUE THREAD

**Issue by ColligenceLabs** [open-quantum-safe/openssl#357]
I'd like to use OQS algorithms to OpenVPN TLS control channel (--tls-auth option) but can't so far.
Still no plans for it ?

**Comment by baentsch** [comment]
> I'd like to use OQS algorithms to OpenVPN TLS control channel (--tls-auth option) but can't so far. Still no plans for it ?

No, we don't have the bandwidth to dive into all downstream projects. What would be helpful here is code showing what exactly fails -- independent of OpenVPN, i.e., concrete `openssl` commands/calls.

**Comment by baentsch** [comment]
FWIW: Just added a (passing) test to run `x509` pubkey extract and `dgst` sign/verify cycle to [oqsprovider](https://github.com/open-quantum-safe/oqs-provider): You may want to check out the code [here](https://github.com/open-quantum-safe/oqs-provider/blob/mb-cms/scripts/oqsprovider-cmssign.sh) to see if these `openssl dgst` commands are the ones you need to have working (as per https://github.com/open-quantum-safe/openssl/issues/295#issuecomment-805848450). Apologies for not adding the same effort to OQS-OpenSSL1.1.1 but for new (OQS-openssl) functionality my preference is to focus on a more future-proof code base (i.e., OpenSSL 3.x). Please let us know why this wouldn't work for you and provide concrete (oqs-openssl111-based) commands that don't work. Until then, closing the issue.
