### ISSUE TITLE
Dilithium2 incorrectly marked as level 1

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssl#378]
https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/oqs-template/oqs-sig-info.md

**Comment by baentsch** [comment]
The issue stems from https://github.com/open-quantum-safe/openssl/blob/907fdfd3e66cbde3b02584bb4c404161e50512af/oqs-template/generatehelpers.py#L68-L76 treating both NIST L1 and L2 as "128 bits security". Is this right or wrong? If wrong, the documentation regarding hybrids must be changed, too:

> if <SIG> claims NIST L1 or L2 security, then the fork provides the methods rsa3072_<SIG> and p256_<SIG>, which combine <SIG> with RSA3072 and with ECDSA using NIST's P256 curve respectively.

If right, we might document "L2" for dilithium2 but without any implications as to any code operations (incl. the classic algs used in hybrid).

**Comment by dstebila** [comment]
Officially, level 2 means computational resources equivalent to a collision search on a 256-bit hash function such as SHA-256.  For a single bit-security metric level 1 and 2 both have 128 bit security, although a more granular resource estimate would view level 2 as having a higher resource requirement than level 1.  For our purposes, it is fine to continue viewing level 2 as 128-bit security and pairing it with AES128 and SHA256 / SHA3-256.
