### ISSUE TITLE
Why the "4 bytes encoding the size of the classical artefact"

### ISSUE THREAD

**Issue by mcarrickscott** [open-quantum-safe/openssl#379]
In the hybrid case signatures and keys are prefixed with a 4-byte length field, being the length of the "classical artifact". So for a p256-dilithium2 hybrid the classical artifact would be p256. However given that we know the overall length, and the fixed length for dilithium2, the encoding length for p256 can already be determined. So the 4-byte field is redundant. Also in the simple non-hybrid case for p256 such a length field was never required, so why is it needed here?

**Comment by dstebila** [comment]
We'd want to use the same encoding across all hybrid combinations.  If I'm not mistaken, there are algorithms which have variable length signatures and keys both on the pre-quantum (RSA) and post-quantum (Falcon) side, so it is not always possible to infer lengths. 

> Also in the simple non-hybrid case for p256 such a length field was never required, so why is it needed here?

The length field is actually present: in the `CertificateVerify` message, for example, the signature is `opaque signature<0..2^16-1>` which would be encoded with a 2-byte length prefix.

**Comment by mcarrickscott** [comment]
Makes sense. Thanks.
