### ISSUE TITLE
p256-Dilithium2 hash function

### ISSUE THREAD

**Issue by mcarrickscott** [open-quantum-safe/openssl#380]
From the documentation* this hybrid should be using SHA2-256 to hash the data before it is signed by p256, but in fact it uses SHA2-384. This may have something to do with the issue around labelling Dilithium2 as level 1 rather than level 2? Personally I would have thought it was level 1, but am happy to be corrected.

*   In addition to post-quantum (PQ) signatures; we also support classical/PQ hybrids. In that case, a classical and a PQ signature
   are generated on the same data, and the resulting signatures are concatenated; the classical and PQ keys are also concatenated
   when serialized. The signed data is first hashed using the SHA-2 hash function matching the security level of the OQS scheme
   (SHA256 for L1, SHA384 for L2/L3, SHA512 for L4/L5) before being signed by the classical algorithm (which can't support
   arbitrarily long messages), and is passed directly to the OQS signature API.

**Comment by dstebila** [comment]
Dilithium2 is claimed level 2 as per the Dilithium submission. 

We do have some inconsistencies around this in our documentation (see e.g. https://github.com/open-quantum-safe/openssl/issues/378) that need to be fixed.

**Comment by mcarrickscott** [comment]
P256 with SHA2-384 is not a standard scheme in TLS1.3. But I guess adherence to existing standards is not really necessary in this context.
