### ISSUE TITLE
Issues when configuring the package for build

### ISSUE THREAD

**Issue by opencrypto** [open-quantum-safe/openssl#393]
I am having issues with the configuration of the library. Specifically, when running the command to generate the needed objects, I run into issues with the SIKE/SIDH algorithms:

```
LIBOQS_DOCS_DIR=../liboqs-0.7.2/docs python3 oqs-template/generate.py
Code generation complete. Be sure to run `make generate_crypto_objects` if required.
Traceback (most recent call last):
  File ".../openssl-OQS-OpenSSL-1_1_1-stable-snapshot-2022-08/oqs-template/generate.py", line 130, in <module>
    import generate_oid_nid_table
...
```
A quick fix seems to be removing the SIDH/SIKE family from the generate.yml file and comment out the following line for the python dictionary in the generate.py script:
```
    liboqs_kems['SIDH']=liboqs_kems['SIKE']
```

**Comment by baentsch** [comment]
Thanks for the bug report. Looks like I switched too fast from "Pre-release" to "Release" :-( 
@opencrypto: Please confirm #394 fixes your problem.
@dstebila  @christianpaquin : Please check update to [release wiki](https://github.com/open-quantum-safe/openssl/wiki/Release-process) and help decide whether this warrants a re-release of oqs-openssl and all downstream components.

**Comment by dstebila** [comment]
> Thanks for the bug report. Looks like I switched too fast from "Pre-release" to "Release" :-( @opencrypto: Please confirm #394 fixes your problem. @dstebila @christianpaquin : Please check update to [release wiki](https://github.com/open-quantum-safe/openssl/wiki/Release-process) and help decide whether this warrants a re-release of oqs-openssl and all downstream components.

My initial response would have been no about re-release, because I would have said that only we run oqs-template, not external users. But since this was found by an external user, obviously I don't understand how people are using this. Let me ask: @opencrypto what led you to run this script?
