### ISSUE TITLE
Do the hybrid X.509 certificates conform to the official ITU-T X.509 multiple algorithm certificates?

### ISSUE THREAD

**Issue by JoaoDiogoDuarte** [open-quantum-safe/openssl#396]
Hello,

I was wondering whether the draft RFC by [Truskovsky et al.](https://datatracker.ietf.org/doc/html/draft-truskovsky-lamps-pq-hybrid-x509-01) concerning hybrid/multiple algorithms X.509 certificates is implemented in this openssl fork, please?

The reason why I ask is because this RFC has been incorporated into the official [ITU-T X.509](https://www.itu.int/rec/T-REC-X.509-201910-I/en) standard since 2019 (see section 9.8) and I only seem to find implementations of[ Bindel et al.'s X.509 hybrid certificates](https://joss.theoj.org/papers/10.21105/joss.01606.pdf). 

The incorporation of the RFC is a bit sneaky because they call the post-quantum algorithm "alternative algorithm". See this [pdf](https://www.itu.int/en/ITU-T/Workshops-and-Seminars/2022/0509/Documents/Jean-Paul%20Lemaire_Public.pdf ) by ITU-T for a recap of X509 history.

Thanks!
Joao

**Comment by dstebila** [comment]
The current hybrid X.509 format in our fork is bespoke. It's our intention to move to whatever emerges as a standard.  

I am confused that you referred to the Truskovsky document as an RFC -- it's only an Internet-Draft, and a seemingly expired one at that.  There are some subsequent documents that are under development -- [1](https://datatracker.ietf.org/doc/draft-ounsworth-pq-composite-sigs/), [2](https://datatracker.ietf.org/doc/draft-ounsworth-pq-composite-keys/) -- which would probably be what we implement, unless a different direction emerges.

**Comment by JoaoDiogoDuarte** [comment]
Sorry for the confusion my original issue, what I mean is that a standard _has_ emerged and I don't know if anyone has really noticed it.

ITU-T has a standardised way of handling multiple algorithms certificates (i.e. hybrid) in 2019. It is based on the expired draft I linked.

I was wondering if that is what you guys implemented?
