### ISSUE TITLE
make test fails

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssl#40]
"make test" fails on OQS-OpenSSL_1_1_1-stable (and not on the upstream's OpenSSL_1_1_1-stable branch)

**Comment by christianpaquin** [comment]
"make test" failures:
../test/recipes/70-test_clienthello.t            (Wstat: 256 Tests: 1 Failed: 1)
  Failed test:  1
  Non-zero exit status: 1
../test/recipes/99-test_fuzz.t                   (Wstat: 256 Tests: 11 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1

**Comment by christianpaquin** [comment]
Fixed in PR #41.

**Comment by dstebila** [comment]
Resolved by #41
