### ISSUE TITLE
Create MD test cases

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/openssl#400]
Equivalent to https://github.com/open-quantum-safe/oqs-provider/issues/70 and in completion of https://github.com/open-quantum-safe/openssl/pull/398#issuecomment-1267020825 implement tests for creating QSC/hybrid signatures/certificates with classic message digests other than the default ones built-in (incl. MD-"NULL" enabled via #398).

**Comment by dstebila** [comment]
The OpenSSL project has indicated that OpenSSL 1.1.1 will reach end-of-life in September 2023.  As such, we are discontinuing development on OQS-OpenSSL 1.1.1, and recommend all users switch to OpenSSL 3 and the [OQS Provider for OpenSSL 3](https://github.com/open-quantum-safe/oqs-provider/), which provides all the same functionality that OQS-OpenSSL 1.1.1 does.  Hence we are closing open pull requests and issues in OQS-OpenSSL 1.1.1 as won't-fix.
