### ISSUE TITLE
Upgrade to OpenSSL 1.1.1s

### ISSUE THREAD

**Issue by dstebila** [open-quantum-safe/openssl#404]

**Comment by baentsch** [comment]
Will do tomorrow or so when/if this release isn't getting withdrawn again.

**Comment by loganaden** [comment]
While attempting the merge:

Auto-merging test/v3ext.c
CONFLICT (content): Merge conflict in test/v3ext.c
Auto-merging test/sslapitest.c
CONFLICT (content): Merge conflict in test/sslapitest.c
Auto-merging test/ec_internal_test.c
CONFLICT (content): Merge conflict in test/ec_internal_test.c
Auto-merging test/clienthellotest.c
CONFLICT (content): Merge conflict in test/clienthellotest.c
Auto-merging test/build.info
Auto-merging ssl/t1_lib.c
Auto-merging ssl/statem/statem_srvr.c
Auto-merging ssl/statem/statem_local.h
Auto-merging ssl/statem/statem_clnt.c
Auto-merging ssl/statem/extensions_srvr.c
CONFLICT (content): Merge conflict in ssl/statem/extensions_srvr.c
Auto-merging ssl/statem/extensions_clnt.c
CONFLICT (content): Merge conflict in ssl/statem/extensions_clnt.c
Auto-merging ssl/ssl_local.h
Auto-merging ssl/ssl_lib.c
Auto-merging ssl/ssl_ciph.c
CONFLICT (content): Merge conflict in ssl/ssl_ciph.c
Auto-merging ssl/s3_lib.c
Auto-merging ssl/record/rec_layer_s3.c
CONFLICT (content): Merge conflict in ssl/record/rec_layer_s3.c
Auto-merging include/openssl/ssl.h
CONFLICT (content): Merge conflict in include/openssl/ssl.h
Auto-merging include/openssl/opensslv.h
CONFLICT (content): Merge conflict in include/openssl/opensslv.h
Auto-merging include/openssl/obj_mac.h
Auto-merging doc/man3/X509_STORE_CTX_new.pod
CONFLICT (content): Merge conflict in doc/man3/X509_STORE_CTX_new.pod
Auto-merging doc/man3/EVP_EncryptInit.pod
CONFLICT (content): Merge conflict in doc/man3/EVP_EncryptInit.pod
Auto-merging doc/man1/x509.pod
CONFLICT (content): Merge conflict in doc/man1/x509.pod
Auto-merging crypto/x509v3/v3_utl.c
Auto-merging crypto/x509v3/v3_addr.c
Auto-merging crypto/x509/x_all.c
CONFLICT (content): Merge conflict in crypto/x509/x_all.c
Auto-merging crypto/x509/x509_vfy.c
Auto-merging crypto/rand/rand_vms.c
CONFLICT (content): Merge conflict in crypto/rand/rand_vms.c
Auto-merging crypto/rand/rand_unix.c
Auto-merging crypto/rand/rand_lib.c
CONFLICT (content): Merge conflict in crypto/rand/rand_lib.c
Auto-merging crypto/pem/pem_lib.c
CONFLICT (content): Merge conflict in crypto/pem/pem_lib.c
Auto-merging crypto/objects/obj_xref.h
Auto-merging crypto/objects/obj_dat.h
Auto-merging crypto/evp/p_lib.c
Auto-merging crypto/evp/e_aes.c
Auto-merging crypto/err/openssl.txt
Auto-merging crypto/ec/ec_key.c
Auto-merging apps/x509.c
CONFLICT (content): Merge conflict in apps/x509.c
Auto-merging apps/speed.c
Auto-merging apps/s_time.c
Auto-merging apps/s_cb.c
CONFLICT (content): Merge conflict in apps/s_cb.c
Auto-merging apps/ca.c
CONFLICT (content): Merge conflict in apps/ca.c
Auto-merging apps/apps.c
Auto-merging README
CONFLICT (content): Merge conflict in README
Auto-merging NEWS
CONFLICT (content): Merge conflict in NEWS
Auto-merging Configurations/windows-makefile.tmpl
Auto-merging Configurations/unix-Makefile.tmpl
CONFLICT (content): Merge conflict in Configurations/unix-Makefile.tmpl
Auto-merging Configurations/10-main.conf
CONFLICT (content): Merge conflict in Configurations/10-main.conf
Auto-merging CHANGES
CONFLICT (content): Merge conflict in CHANGES
Auto-merging .gitmodules
CONFLICT (add/add): Merge conflict in .github/workflows/windows.yml
Auto-merging .github/workflows/windows.yml
CONFLICT (add/add): Merge conflict in .github/workflows/run-checker-merge.yml
Auto-merging .github/workflows/run-checker-merge.yml
CONFLICT (add/add): Merge conflict in .github/workflows/run-checker-daily.yml
Auto-merging .github/workflows/run-checker-daily.yml
CONFLICT (add/add): Merge conflict in .github/workflows/run-checker-ci.yml
Auto-merging .github/workflows/run-checker-ci.yml
CONFLICT (add/add): Merge conflict in .github/workflows/cross-compiles.yml
Auto-merging .github/workflows/cross-compiles.yml
Auto-merging .github/workflows/ci.yml
CONFLICT (content): Merge conflict in .github/workflows/ci.yml

**Comment by loganaden** [comment]
@baentsch it's not as straightforward as we thought it would. Do you guys have a slack channel or something ? If you don't, that's fine. We'll try to figure out how to fix this.

**Comment by baentsch** [comment]
Sorry, no Slack channel. We use github to communicate. The above is quite normal: oqs-openssl and upstream openssl have different, sometimes conflicting code paths (one of the reasons for starting the work on the stand-alone oqs-provider). All these conflicts need to be resolved as part of the work on the PR: Often it's simple (comment changes), sometimes it requires deeper understanding of the logic: It is a good exercise to get acquainted with the project, but may require some effort at the start. 
One more hint: After resolving all conflicts, be sure to successfully run `python3 oqs-template/generate.py && make generate_crypto_objects && make test && LD_LIBRARY_PATH=. python3 -m pytest oqs-test/test_tls_full.py`.

**Comment by baentsch** [comment]
@loganaden : Can I ask how things are going for you? Any questions? Problems? I'd be glad to help you get up to speed and on-board as an active contributor if that'd be your goal.

**Comment by baentsch** [comment]
@loganaden Any news regarding your suggested contribution? Our goal would be to close this within the next two weeks: Will you/your team have time to do this until then? Alternatively, I'd be happy to do it. Please just let us know.

**Comment by loganaden** [comment]
@baentsch I got taken up. Sorry, please go ahead.

**Comment by baentsch** [comment]
> @baentsch I got taken up. Sorry, please go ahead.

Thanks for letting me know. In case you'd like to take a look: #407
