### ISSUE TITLE
Add hybrid KEX to speed

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/openssl#408]
Prerequisite for https://github.com/open-quantum-safe/profiling/issues/83

**Comment by baentsch** [comment]
After some digging my conclusion is that hybrid KEM testing in this code base isn't exactly straightforward: Hybrid KEMs were added straight into the TLS logic without a point where to only call that logic for `speed` testing: https://github.com/open-quantum-safe/openssl/commit/b05b1b75cbb6b07fe5c386301800ee705c30b3ac . Thus, this should be re-factored to allow [the oqs-openssl KEM speed logic](https://github.com/open-quantum-safe/openssl/blob/82b5b1dcd786e13e3af8fe23823dedf2ed25d206/apps/speed.c#L3376-L3449) to directly call it. Anything else would arguably be artificial (as is the current code if we're honest). Side note: Implementing this in openssl3 would be much simpler as all KEMs (hybrid, PQ, or anything else) are standalone entities (that [could be `speed` tested](https://github.com/openssl/openssl/issues/19535)).

**Comment by dstebila** [comment]
The OpenSSL project has indicated that OpenSSL 1.1.1 will reach end-of-life in September 2023.  As such, we are discontinuing development on OQS-OpenSSL 1.1.1, and recommend all users switch to OpenSSL 3 and the [OQS Provider for OpenSSL 3](https://github.com/open-quantum-safe/oqs-provider/), which provides all the same functionality that OQS-OpenSSL 1.1.1 does.  Hence we are closing open pull requests and issues in OQS-OpenSSL 1.1.1 as won't-fix.
