### ISSUE TITLE
Make OID's settable (?)

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/openssl#409]
As per the discussion [here](https://github.com/IETF-Hackathon/pqc-certificates/issues/3#issuecomment-1325652216) it may be advisable to add to oqs-openssl111 the ability to set OIDs dynamically to integrate it into interoperability testing setups. For reference, [oqs-provider already has this capability](https://github.com/open-quantum-safe/oqs-provider/blob/main/ALGORITHMS.md#oids).

General question: Do we want oqs-openssl111 participate in interop testing? If no, this issue can be closed as "wontfix".

**Comment by dstebila** [comment]
The OpenSSL project has indicated that OpenSSL 1.1.1 will reach end-of-life in September 2023.  As such, we are discontinuing development on OQS-OpenSSL 1.1.1, and recommend all users switch to OpenSSL 3 and the [OQS Provider for OpenSSL 3](https://github.com/open-quantum-safe/oqs-provider/), which provides all the same functionality that OQS-OpenSSL 1.1.1 does.  Hence we are closing open pull requests and issues in OQS-OpenSSL 1.1.1 as won't-fix.
