### ISSUE TITLE
Implementation of Composite Keys and Encryption

### ISSUE THREAD

**Issue by JoaoDiogoDuarte** [open-quantum-safe/openssl#432]
Hello,

I came across [this article](https://www.cybertrust.co.jp/blog/rd/pqc/qqs-hybrid-certificate.html) discussing X.509 certificates in openssl-oqs. It's in Japanese, so I've taken the liberty to translate it through Google Translate, [link is here](https://translate.google.com/translate?sl=auto&tl=en&hl=en-US&u=https://www.cybertrust.co.jp/blog/rd/pqc/qqs-hybrid-certificate.html&client=webapp).

Essentially, they are claiming that you all already implement the following IETF (expired) drafts:

1. [draft-ounsworth-pq-composite-encryption](https://datatracker.ietf.org/doc/draft-ounsworth-pq-composite-encryption/)
2. [draft-ounsworth-pq-explicit-composite-keys](https://datatracker.ietf.org/doc/draft-ounsworth-pq-explicit-composite-keys/)
3. [draft-ounsworth-pq-composite-keys](https://datatracker.ietf.org/doc/draft-ounsworth-pq-composite-keys/)

I was wondering if that is accurate or if you use something different, please?

Thanks!

**Comment by dstebila** [comment]
The composite/hybrid format for signatures/keys/certificates in the current version of OQS-OpenSSL is ad hoc, created before any of these drafts existed, and not the same as those drafts.  It is our intention to move to those formats once they are stable, and I'm aware of some work being done already to prepare a pull request in oqs-provider to update to those formats.
