### ISSUE TITLE
update falcon IDs for openssl 1.1.1

### ISSUE THREAD

**Issue by k-Artin** [open-quantum-safe/openssl#437]
hello 
i want to use tls connection with falcon signature with openssl 1.1.1 (server) and openssl 3 (client).
after this **https://github.com/open-quantum-safe/oqs-provider/pull/125** i can not use this signature (falcon).
please update the falcon (O)IDs in openssl 1.1.1.

Thank you in advance!

**Comment by baentsch** [comment]
Thanks for this reminder. Could I ask you in turn to chime in to [this discussion](https://github.com/open-quantum-safe/openssl/discussions/434)? What are your arguments for keeping maintaining OQS-OpenSSL111? What is it that you cannot do with OpenSSL3+oqsprovider?

**Comment by k-Artin** [comment]
> Thanks for this reminder. Could I ask you in turn to chime in to [this discussion](https://github.com/open-quantum-safe/openssl/discussions/434)? What are your arguments for keeping maintaining OQS-OpenSSL111? What is it that you cannot do with OpenSSL3+oqsprovider?

nothing just i want to remind you.
thank you for updating (O)IDs.
