### ISSUE TITLE
Getting below error while running openssl smime

### ISSUE THREAD

**Issue by Jpgig** [open-quantum-safe/openssl#439]
Hello, When I am running below command for openssl smime, getting an error as captured in the screenshot:
**command :** 

/home/jiten/oqs/openssl/apps/openssl smime -sign -in governance_pqc_dl3.xml -text -out governance.smime -signer maincacert_pqc_dl3.pem -inkey maincakey_pqc_dl3.pem

Error message : 
![image](https://user-images.githubusercontent.com/115164852/233670096-93577f17-6c80-4404-b6b0-49ab2fb4870f.png)
[required_files.zip](https://github.com/open-quantum-safe/openssl/files/11296988/required_files.zip)

**Comment by baentsch** [comment]
Could you please try to reproduce this error using the more well-supported OpenSSL3+oqsprovider? Simplest probably would be by using the docker Image 'openquantumsafe/oqs-ossl3' for this.

**Comment by Jpgig** [comment]
Thanks. This worked.
