### ISSUE TITLE
Confusing wording in Code generation wiki page

### ISSUE THREAD

**Issue by Martyrshot** [open-quantum-safe/openssl#441]
When enabling algorithms, compilation errors occur when too many are enabled. The wiki page states:
```
If a signature algorithm variant that is disabled by default is to be enabled, simply change the enable value of that variant in oqs-template/generate.yml from false to true, keeping in mind that at most 64 variants can be enabled at a time.
```
However the number of variants appears to be much less than 64. Is the maximum number of variants inclusive of the non-pqc algorithms that ship with openssl? If so I think it would be useful to mention that, and perhaps mention how many pqc variants can be enabled separately.

**Comment by dstebila** [comment]
Yes, the maximum number includes all the non-PQC algorithm that ship with OpenSSL.  I think based on https://github.com/open-quantum-safe/openssl/blob/1e13c8cb261089fe49120e23b91fc666d562f45b/ssl/ssl_local.h#L447-L457 there are 9 slots taken up by non-PQC algorithms, but I'm not 100% sure. @xvzcf @christianpaquin or @baentsch are you able to confirm?

**Comment by baentsch** [comment]
Confirmed. 9 PK algs is a hardcoded limitation in OpenSSL1 that I changed with a PR in OpenSSL3. Hence this limitation does not exist with the oqsprovider.

**Comment by dstebila** [comment]
Okay, I've added a line to the wiki explaining this.

**Comment by Martyrshot** [comment]
Thank you!
