### ISSUE TITLE
Build failure on platforms running OpenSSL3 by default

### ISSUE THREAD

**Issue by baentsch** [open-quantum-safe/openssl#442]
After https://github.com/open-quantum-safe/liboqs/pull/1431 landed, `liboqs`gets built with OpenSSL3 symbols when OpenSSL3 is installed by default on the build platform. In consequence, these symbols cannot be found when building `oqs-openssl111` using that `liboqs` (as these symbols are not present in any OpenSSL111 fork).

--> I'd now _strongly_ urge to declare this fork deprecated as the build becomes somewhat convoluted (or surprising):

- (non-oqs) OpenSSL111 must be installed
- liboqs must be built against that OpenSSL111and installed to oqs-openssl111
- only then can a build of oqs-openssl111 succeed

Alternatively, `liboqs` _must_ be built with `-DOQS_USE_OPENSSL=OFF` -- which I'd call at least "surprising" for a build of `oqs-openssl`.

**Comment by dstebila** [comment]
Okay, that is getting worse and worse.

Would you be okay with trying to squeeze out one last release of this fork to match the upcoming liboqs 0.8.0 release, and then deprecate it?

**Comment by baentsch** [comment]
Sure. We can (and need to) "resolve" this issue with a documentation update, then.
