### ISSUE TITLE
Remove references to old algorithms in templating code

### ISSUE THREAD

**Issue by xvzcf** [open-quantum-safe/openssl#448]
There are still some references to SIKE, Rainbow, etc. in the `oqs-template` folder (and possibly elsewhere); just making an issue here so as to not lose track.

**Comment by dstebila** [comment]
The OpenSSL project has indicated that OpenSSL 1.1.1 will reach end-of-life in September 2023.  As such, we are discontinuing development on OQS-OpenSSL 1.1.1, and recommend all users switch to OpenSSL 3 and the [OQS Provider for OpenSSL 3](https://github.com/open-quantum-safe/oqs-provider/), which provides all the same functionality that OQS-OpenSSL 1.1.1 does.  Hence we are closing open pull requests and issues in OQS-OpenSSL 1.1.1 as won't-fix.
