### ISSUE TITLE
make install_dev attempts to install oqs headers that are not part of the source tree

### ISSUE THREAD

**Issue by maxcraft** [open-quantum-safe/openssl#452]
File: Configurations/unix-Makefile.tmpl
Line 617-623
Branch: https://github.com/open-quantum-safe/openssl/blob/OQS-OpenSSL_1_1_1-stable/Configurations/unix-Makefile.tmpl

Those line cause `make install_dev` fail, because oqs directory is not part of the source tree. The headers are part of liboqs and, by the time the make command is executed, are already installed.

**Comment by baentsch** [comment]
Thanks for making us aware of this issue. However, we're ceasing support of this OpenSSL111 fork, so don't encourage using `make install_dev`, and invite all users to move to OpenSSL3 (using [oqs-provider](https://github.com/open-quantum-safe/oqs-provider)) instead.

**Comment by dstebila** [comment]
The OpenSSL project has indicated that OpenSSL 1.1.1 will reach end-of-life in September 2023.  As such, we are discontinuing development on OQS-OpenSSL 1.1.1, and recommend all users switch to OpenSSL 3 and the [OQS Provider for OpenSSL 3](https://github.com/open-quantum-safe/oqs-provider/), which provides all the same functionality that OQS-OpenSSL 1.1.1 does.  Hence we are closing open pull requests and issues in OQS-OpenSSL 1.1.1 as won't-fix.
