### ISSUE TITLE
openssl ciphers not displaying the OQS supported ciphers.

### ISSUE THREAD

**Issue by crypto-keys-unlocked** [open-quantum-safe/openssl#457]
I have installed the oqs library in a pc globally but isn't it possible to get the oqs supported algorithms in the ciphersuite as well?
`$ openssl version.
Here is the demo.
OpenSSL 1.1.1u  30 May 2023, Open Quantum Safe 2023-05`

But,
`openssl ciphers 
TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:RSA-PSK-AES256-GCM-SHA384:DHE-PSK-AES256-GCM-SHA384:RSA-PSK-CHACHA20-POLY1305:DHE-PSK-CHACHA20-POLY1305:ECDHE-PSK-CHACHA20-POLY1305:AES256-GCM-SHA384:PSK-AES256-GCM-SHA384:PSK-CHACHA20-POLY1305:RSA-PSK-AES128-GCM-SHA256:DHE-PSK-AES128-GCM-SHA256:AES128-GCM-SHA256:PSK-AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:ECDHE-PSK-AES256-CBC-SHA384:ECDHE-PSK-AES256-CBC-SHA:SRP-RSA-AES-256-CBC-SHA:SRP-AES-256-CBC-SHA:RSA-PSK-AES256-CBC-SHA384:DHE-PSK-AES256-CBC-SHA384:RSA-PSK-AES256-CBC-SHA:DHE-PSK-AES256-CBC-SHA:AES256-SHA:PSK-AES256-CBC-SHA384:PSK-AES256-CBC-SHA:ECDHE-PSK-AES128-CBC-SHA256:ECDHE-PSK-AES128-CBC-SHA:SRP-RSA-AES-128-CBC-SHA:SRP-AES-128-CBC-SHA:RSA-PSK-AES128-CBC-SHA256:DHE-PSK-AES128-CBC-SHA256:RSA-PSK-AES128-CBC-SHA:DHE-PSK-AES128-CBC-SHA:AES128-SHA:PSK-AES128-CBC-SHA256:PSK-AES128-CBC-SHA`

**Comment by baentsch** [comment]
Two comments:
1) OQS does not implement ciphers, but only KEM and signature algorithms
2) (oqs-)openssl111 is being phased out -- please use OpenSSL3 and [oqs-provider](https://github.com/open-quantum-safe/oqs-provider). The relevant checks there are `openssl list -signature-algorithms` and `openssl list -kem-algorithms` (assuming you built and installed "oqsprovider").

**Comment by crypto-keys-unlocked** [comment]
Thank you for your response. However I have another doubt if I try to install OpenVPN with the newly built oqs-provider  will I be able to establish TLS key exchange with pq algorithms?

**Comment by baentsch** [comment]
> Thank you for your response. However I have another doubt if I try to install OpenVPN with the newly built oqs-provider will I be able to establish TLS key exchange with pq algorithms?

Why do you have this doubt? This has already been done: https://github.com/open-quantum-safe/oqs-demos/tree/main/openvpn.
