### ISSUE TITLE
Question: How do I verify that a connection uses a quantum kem in OQS-OpenSSL_1_0_2-stable

### ISSUE THREAD

**Issue by fwh-dc** [open-quantum-safe/openssl#460]
Hi,

I know the branch is deprecated, but I am studying the implementation to understand what is required to support quantum kems in TLS1.2/DTLS1.2.

So I've built the OQS-OpenSSL_1_0_2-stable version and now I want to verify that a quantum kem is used by the tls key exchange.

Should I just look at the s_client output
```
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : OQSKEM-DEFAULT-ECDHE-RSA-AES256-GCM-SHA384
```
In order to verify that a quantum kem was used?
And is there a way to change the quantum kem? From the source code it looks like the default kem maps to a SIKE variant, and I'd like to test with Kyber. My assumption is I just change the definition OQS_KEM_DEFAULT in liboqs?

Here are the commands I used:
```
./apps/openssl s_server -cert rsa_srv.crt -key rsa_srv.key -tls1_2
./apps/openssl s_client -tls1_2 -cipher OQSKEM-DEFAULT-ECDHE-RSA-AES256-GCM-SHA384
```

**Comment by baentsch** [comment]
> My assumption is I just change the definition OQS_KEM_DEFAULT in liboqs?

Probably right. But we removed the concept of default algs quite some time ago from `liboqs`, so you'd (also) only be able to use pretty dated versions of `liboqs`.

May I ask what is your rationale to dive into such old versions of the code (and TLS)?

**Comment by fwh-dc** [comment]
As I previously stated in https://github.com/open-quantum-safe/openssl/issues/454 I am interested in the support of quantum key exchanges in DTLS. 

As a first step: I wanted to check if quantum key exchanges is supported in DTLS1.2 with the implementation in OQS-OpenSSL_1_0_2-stable. And it looks like DTLS is supported in this old revision if what I posted is the correct way to verify that a connection was established with a quantum kem.

Now I'd like to understand the best way to achieve the overall goal of DTLS support. I'd like to hear from you if you think there's something I need to know? Otherwise I will continue studying past and present implementations to get up to speed on the OpenSSL implementation.

**Comment by dstebila** [comment]
If memory serves, we never worked on or tested DTLS, even in this old branch. Maybe it works, maybe it doesn't. 

As for seeing if a post-quantum key exchange is being used, you can use use some of the s_client and s_server command line options to print out what algorithms end up being used, and you can also inspect the connection in Wireshark; though an unmodified Wireshark will not recognize the algorithm identifiers used, it should still at least say something like "unknown algorithm" which would be an indication that post-quantum was being used.
