### ISSUE TITLE
Unable to build in M2 MacBook Air

### ISSUE THREAD

**Issue by PrabhasKmrGH** [open-quantum-safe/openssl#467]
Because of 65536 characters limit I can't show all of the output so I'm attaching `.md` file inwhich it is written. I apologies for any inconvenience.

[My steps.md](https://github.com/open-quantum-safe/openssl/files/15463882/My.steps.md)

**Comment by cothan** [comment]
Hi, 

It's seem like you have successful built and installed the library. 
Can you clarify what is the problem you're facing with? 


P/S: Next time, please write down the steps and shorten the build log so it fits in the post, please don't attach 1MB file and expect others download and open it, for me it's security reasons.

**Comment by PrabhasKmrGH** [comment]
I can’t seem to use Kyber for Post-Quantum Encryption. I have never tried this before and sought help from ChatGPT. I understand that ChatGPT is a predictive model and may sometimes be inaccurate. According to ChatGPT, it is not recognizing Liboqs. If my steps were wrong, could you please provide the correct steps for using Kyber encryption?

I once again apologize for any inconvenience and will ensure to include shorter logs in the message body instead of attaching files in the future.

Edit: Do I need to have OpenSSL if all I want to do is to have a compiled C programs which would generate key pairs, Encrypt files on given folder location & Decrypt files on given for del location locally?

**Comment by cothan** [comment]
Oh, i realize this is the only issue in the this repository. 
You're building OpenSSL 1.1 with liboqs, which is no longer SUPPORTED.
Can you try oqs-provider and close this issue?

**Comment by PrabhasKmrGH** [comment]
Alright.
