### ISSUE TITLE
liboqs as a submodule?

### ISSUE THREAD

**Issue by tlepoint** [open-quantum-safe/openssl#5]
I just realized that the liboqs code is redundant in this repository; should we add liboqs as a git submodule rather than copy/pasting all the code?

**Comment by dstebila** [comment]
Originally I had put it in as a submodule, but then a few people contacted me that when they did a basic clone or download from Github, the submodule didn't get checked out with it.  I had put an instruction in the README, but still people had trouble.  So I decided to just put a copy of the code into the repository instead.

**Comment by tlepoint** [comment]
Maybe instead of a submodule, we could provide a script to run after configure, or something like that?

**Comment by dstebila** [comment]
Is there a specific concern you have about having the redundant code, rather than just the general software engineering principle of avoiding repetition?

**Comment by tlepoint** [comment]
Not particularly... It makes weird PRs too (cf. #4 where the liboqs code is not updated).

**Comment by dstebila** [comment]
Maybe we could make it part of configure?  So put it as a submodule (which is the proper thing to do) and then have configure pull the sub-module if it isn't already there?

**Comment by dstebila** [comment]
In both our current OpenSSL branches (OQS-master and OQS-OpenSSL-1_0_2-stable), the source code of liboqs is not duplicated, nor is it a git subtree / submodule, instead liboqs would be built by the developer as a dependency and then pointed to at OpenSSL configure time.
