### ISSUE TITLE
OpenSSL 1.0.2 build failure on Windows

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssl#52]
First error is that `oqs/oqs.h` can't be found while building `ssl3.h`.

**Comment by christianpaquin** [comment]
Fixed by PR #53.

**Comment by smashra** [comment]
Openssl build is getting error on mac:
=============
gcc  -Iinclude -pthread -m64 -fPIC -DNDEBUG  -MMD -MF fuzz/asn1.d.tmp -MT
fuzz/asn1.o -c -o fuzz/asn1.o fuzz/asn1.c
gcc  -Iinclude -pthread -m64 -fPIC -DNDEBUG  -MMD -MF
fuzz/test-corpus.d.tmp -MT fuzz/test-corpus.o -c -o fuzz/test-corpus.o
fuzz/test-corpus.c
engines/e_afalg.c:24:10: fatal error: 'linux/version.h' file not found
#include <linux/version.h>
         ^~~~~~~~~~~~~~~~~
==================

**Comment by dstebila** [comment]
I can't reproduce the error you experienced, @smashra: it builds fine for me on my Mac.

**Comment by smashra** [comment]
Apologies, my bad.

There is no problem.
