### ISSUE TITLE
Can't build Windows DLL target on 1.0.2

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/openssl#58]
Running `nmake -f ms\ntdll.mak` (instead of `nt.mak`, as described in the README.md) fails; many `unresolved external symbol OQS_KEM_*` errors. liboqs must be correctly linked in this makefile to fix this.

**Comment by dstebila** [comment]
Is this blocking for release?

**Comment by christianpaquin** [comment]
It's highly desirable. The issue is that the Windows support code from the OpenSSL_1_0_2-stable branch has not been ported to the OQS-... branch. I should be able to address that today; if not, I'll update the README to say the DLL target isn't supported.

**Comment by christianpaquin** [comment]
PR #60 fixes this. 1.0.2 should be ready for RC3

**Comment by dstebila** [comment]
Resolved by #60
