### ISSUE TITLE
Question about update OpenSSL in Package-Manager after compile OpenSSL Quantum

### ISSUE THREAD

**Issue by ghost** [open-quantum-safe/openssl#85]
Hi!

Can I easily update the following OpenSSL packages in my package-manager after compiling OpenSSL Quantum myself and installed it.

My package-manager shows me new updates of: 
- openssl
- openssl-devel
-openssl-libs
-openssl-pkcs11

Or I always have to compile and install updates of OpenSSL Quantum myself?
Not that I'm overwriting OpenSSL Quantum.

**Comment by christianpaquin** [comment]
Given the experimental nature of the post-quantum cryptography integration, developers must currently build and deploy the OpenSSL fork manually.
