### ISSUE TITLE
Error in $ make -j

### ISSUE THREAD

**Issue by jaimesaez97** [open-quantum-safe/openssl#97]
I receive an error 
on the OpenSSL fork built `$ make -j` execution:

![error2](https://user-images.githubusercontent.com/33544051/60010523-40dd5600-9678-11e9-94fb-cc95cb84efdd.PNG)
![error1](https://user-images.githubusercontent.com/33544051/60010522-40dd5600-9678-11e9-9764-c682cb8b81c6.PNG)

¿Any help? Thanks!

**Comment by xvzcf** [comment]
This is a bug that is being addressed by https://github.com/open-quantum-safe/openssl/pull/95.

**Comment by dstebila** [comment]
#95 is merged, which should fix this.  Please reopen if it doesn't.
